//action stuff weeee
exports.handP = [
  'http://i2.kym-cdn.com/photos/images/newsfeed/000/932/422/4ad.gif',
  'http://i1.kym-cdn.com/photos/images/newsfeed/000/932/364/770.gif',
  'https://media.giphy.com/media/ZaaGHJGe4QJyM/giphy.gif',
  'https://33.media.tumblr.com/tumblr_m4mf3iheM61qfzteso1_500.gif',
  'https://s-media-cache-ak0.pinimg.com/originals/38/83/29/38832988f327dccf6c1c92d70257d0b9.gif',
  'https://s-media-cache-ak0.pinimg.com/originals/d8/4d/a1/d84da12818a8e589d57e0abca64e8559.gif',
  'https://33.media.tumblr.com/fe682131763ed930e62b9133e0e2b9a5/tumblr_nwdi6ojjKI1rveihgo1_500.gif',
  'https://68.media.tumblr.com/d2215d0ea8bf81b43b05ae335b5fa16d/tumblr_onaaq6KFen1vpu8oho1_500.gif',
  'https://images.gr-assets.com/hostedimages/1466200611ra/19452590.gif',
  'http://68.media.tumblr.com/3f55c1fab37cd1c4327778eac21d42b3/tumblr_inline_mte8cnGxEl1rg1ld5.gif',
  'https://38.media.tumblr.com/0663dd718366173ca290754c8ec5dacc/tumblr_ne30n7W5wt1thsnklo3_500.gif',
  'http://i1.kym-cdn.com/photos/images/newsfeed/001/107/453/d9a.png',
  'https://static.fjcdn.com/pictures/Handholding+is+maximum+lewd_53fdb3_5270957.jpg',
  'http://i0.kym-cdn.com/photos/images/original/001/160/602/3d5.png',
  'http://i0.kym-cdn.com/photos/images/masonry/001/217/617/28c.jpg',
  'http://i.imgur.com/86VpZ3H.png',
  'https://i.imgur.com/j0EjBso.png'
]

exports.hugP = [
  'http://i.imgur.com/pZa9Ppe.gif',
  'http://i.imgur.com/QghzxNa.gif',
  'http://i.imgur.com/Z5DpKer.gif',
  'http://i.imgur.com/J9EDW2g.gif',
  'http://i.imgur.com/33GnoBC.gif',
  'http://i.imgur.com/QNNA4M2.gifv',
  'http://i.imgur.com/LWhsSJU.gif',
  'http://i.imgur.com/RRpmeap.gif',
  'http://i.imgur.com/nOuAxhI.gif',
  'http://i.imgur.com/YfkTt9h.gif',
  'http://i.imgur.com/qSejAy0.gifv',
  'http://i.imgur.com/vFwUm3E.gif',
  'http://i.imgur.com/kif6tPp.gif',
  'http://i.imgur.com/QBlUzrl.gif',
  'http://i.imgur.com/NjUA3dn.gif',
  'http://i.imgur.com/x11OYI1.gif',
  'http://i.imgur.com/EVtWJHw.gifv',
  'http://i.imgur.com/UcSS0oZ.gifv',
  'http://i.imgur.com/HNcRPJ7.gifv',
  'http://i.imgur.com/1jZ7TBv.gifv',
  'http://i.imgur.com/P6KLS0T.gifv',
  'http://i.imgur.com/oDNvTyt.gifv',
  'http://i.imgur.com/LZBcwKd.gifv',
  'http://i.imgur.com/CU8uP3Y.gifv',
  'http://i.imgur.com/2Un7CYs.gifv',
  'http://i.imgur.com/xRZ7zg1.gif',
  'http://i.imgur.com/ZzYUNjv.gif',
  'https://i.imgur.com/OGHfXlE.gifv',
  'https://i.imgur.com/KPbKHJ1.gifv',
  'http://i.imgur.com/QdETnvv.gif',
  'http://i.imgur.com/rPoxqas.gif',
  'http://i.imgur.com/iI3o7t0.gif',
  'http://i.imgur.com/hcxDeFZ.gif',
  'http://i.imgur.com/y03B2dL.gif',
  'http://i.imgur.com/la2DSbP.gif',
  'http://i.imgur.com/I8LyQ9L.gif',
  'http://i.imgur.com/SOMVzbs.gif',
  'http://i.imgur.com/YXWnCwv.gif',
  'http://i.imgur.com/Y9CAUOl.gifv',
  'http://i.imgur.com/GYHunne.gif',
  'http://25.media.tumblr.com/668e4508190fb9f62ea9b5eb1d112531/tumblr_mw41ntelfK1s6ghcbo1_500.gif',
  'https://38.media.tumblr.com/91b578f5c95575f088f05be5ee0f284a/tumblr_mlrr92OyU21so32vdo1_500.gif',
  'http://i.imgur.com/WEQjiiT.gif',
  'http://i.imgur.com/w0Phmum.gif',
  'http://i.imgur.com/Mi0m04x.gif',
  'http://i.imgur.com/KN2ahrk.gif',
  'http://i.imgur.com/2v3eUQw.gif',
  'http://i.imgur.com/OIPxM9W.gifv',
  'https://media.giphy.com/media/143v0Z4767T15e/giphy.gif',
  'http://gifimage.net/wp-content/uploads/2017/06/anime-hug-gif-7.gif',
  'https://media.tenor.com/images/da9278d1ae0a39a4932a7a656ba3c73f/tenor.gif',
  'https://media.giphy.com/media/TdXxcoNvHDVu0/giphy.gif',
  'https://s-media-cache-ak0.pinimg.com/originals/c5/85/27/c58527caa736f8d5ce4ab6ee6e3f736b.gif',
  'https://media.tenor.com/images/c67e9d0cf6b9126540c4e490bacbceee/tenor.gif',
  'http://38.media.tumblr.com/e9fae5fd165029c63c6963f855238c1b/tumblr_nqygyy3PNm1uz2l4zo1_500.gif',
  'https://media.giphy.com/media/wnsgren9NtITS/giphy.gif',
  'https://media.giphy.com/media/FjPsUjWAP6CwE/giphy.gif',
  'https://media.giphy.com/media/g139KP9v8PWyk/giphy.gif',
  'https://media.giphy.com/media/od5H3PmEG5EVq/giphy.gif',
  'http://i0.kym-cdn.com/photos/images/original/000/906/455/51f.gif',
  'https://media.giphy.com/media/kvKFM3UWg2P04/giphy.gif',
  'https://media.giphy.com/media/DPDSY2gL0dTqw/giphy.gif',
  'https://media.giphy.com/media/PAnAdRBSnzF8k/giphy.gif',
  'http://gifimage.net/wp-content/uploads/2017/06/anime-hug-gif-17.gif',
  'https://gifimage.net/wp-content/uploads/2017/07/anime-tackle-hug-gif-11.gif',
  'http://i0.kym-cdn.com/photos/images/original/001/110/890/449.gif',
  'https://media.giphy.com/media/NIZKr6XAQWhJC/giphy.gif',
  'https://media.giphy.com/media/bVtGn2g1g3wMo/giphy.gif',
  'http://49.media.tumblr.com/89de7b404cf5cd01663ddd4bcae731a2/tumblr_nw37nuwXGG1r60zuio1_540.gif',
  'http://gifimage.net/wp-content/uploads/2017/01/Anime-hug-GIF-Image-Download-22.gif',
  'https://gifimage.net/wp-content/uploads/2017/07/anime-tackle-hug-gif-3.gif',
  'https://i.imgur.com/yLLtIQ1.gif',
  'https://38.media.tumblr.com/9f6bbded87df598ea76836fbb0db8e6c/tumblr_mymyfha9TL1sm5fjzo1_500.gif',
  'https://discuss.moe/uploads/default/original/1X/fee14c5e1043e4fc134e9f46fbe8675c4576d8c7.gif',
  'https://68.media.tumblr.com/191629f6fffdf4c01ae816c63c1dcbad/tumblr_osksdggPqb1ug37q6o1_500.gif',
  'http://31.media.tumblr.com/33c8d3b0b83514b16fc5fb06589ceb11/tumblr_nlrld1pXss1tros9go1_500.gif',
  'https://s-media-cache-ak0.pinimg.com/originals/65/67/4a/65674a6a3868d0f071352b5932022a2a.gif',
  'http://i.imgur.com/QvypCFg.gif',
  'http://pa1.narvii.com/5864/52f54331ac6a0fe0edb59054c2787bf57f90e1ba_hq.gif'
]

exports.kissP = [
  'https://media.giphy.com/media/FqBTvSNjNzeZG/giphy.gif',
  'https://media.tenor.com/images/289ec1f0b0ee5163758122ed5fc1cb20/tenor.gif',
  'https://media.giphy.com/media/G3va31oEEnIkM/giphy.gif',
  'http://25.media.tumblr.com/8ccc58d2c42dbef8ced3fc747518cffc/tumblr_mxgpinyLDk1t2wbmao1_400.gif',
  'https://media.giphy.com/media/Gj8bn4pgTocog/giphy.gif',
  'https://media.giphy.com/media/JYpVJEcNrDAWc/giphy.gif',
  'https://em.wattpad.com/be664a8e8b471f49798ad367e7e809bea6dff987/68747470733a2f2f73332e616d617a6f6e6177732e636f6d2f776174747061642d6d656469612d736572766963652f53746f7279496d6167652f5470763473634d653344323357413d3d2d3331373535353132392e3134373938323930393132363361666232353737353336373930322e676966?s=fit&w=1280&h=1280',
  'https://media.giphy.com/media/KmeIYo9IGBoGY/giphy.gif',
  'http://24.media.tumblr.com/tumblr_m8yxnswMgE1rc0fd6o1_r5_500.gif',
  'http://pa1.narvii.com/5823/a1ff3fbec588fdde66dd24293f2220233ce42076_hq.gif',
  'https://68.media.tumblr.com/81bba396a3fcaa0e1745b620d44fe358/tumblr_o67xve7qMR1s7fey2o1_500.gif',
  'https://media.tenor.com/images/0de1905e4a8b2bb465d04a1f96df7f85/tenor.gif',
  'https://media.tenor.com/images/caa0f445feb550d64a6ba332b0203817/tenor.gif',
  'http://25.media.tumblr.com/0a969f0c8ac5972ad663fc1a14f4663b/tumblr_mgbyvzpksK1rmdepbo1_500.gif',
  'https://media.giphy.com/media/oHZPerDaubltu/giphy.gif',
  'https://media.tenor.com/images/ab85c1bbd4e884c8fe7a0e05083999f2/tenor.gif',
  'https://media.tenor.com/images/d7542a2525f4d92f1ee0b14c21470665/tenor.gif',
  'https://media.giphy.com/media/8iwfa0XSxDUSQ/giphy.gif',
  'https://s-media-cache-ak0.pinimg.com/originals/fa/73/e7/fa73e737372ef2c422050bbe332f80d1.gif',
  'https://media.tenor.com/images/0d39ba5a64c3ff5484bf3f492fd497ed/tenor.gif',
  'http://data.whicdn.com/images/144335846/original.gif',
  'https://media.tenor.com/images/02a36dc9b1aa8216774f2fe31b97cd33/tenor.gif',
  'https://media.giphy.com/media/sS7Jac8n7L3Ve/giphy.gif',
  'https://media.giphy.com/media/KH1CTZtw1iP3W/giphy.gif',
  'https://s-media-cache-ak0.pinimg.com/originals/ef/cc/cb/efcccb410c47e35559e71c8435505dbc.gif',
  'https://media.giphy.com/media/ll5leTSPh4ocE/giphy.gif',
  'https://media.tenor.com/images/6222e89cd0f86e74ad5dd106bf2da8b4/tenor.gif',
  'https://68.media.tumblr.com/d08bc5bec3ebff5805ae2d984c4eccd5/tumblr_mu5pvnteA41sibpv8o1_500.gif',
  'http://31.media.tumblr.com/tumblr_lmbbn9bKcg1qb3n2io1_500.gif',
  'http://img37.laughinggif.com/pic/HTTP3MyLmZhdmltLmNvbS9vcmlnLzI4L2FpaGFyYS1rb3Rva28tYW5pbWUtaXJpZS1uYW9raS1pdGF6dXJhLW5hLWtpc3MtRmF2aW0uY29tLTIzODk0My5naWYlog.gif',
  'https://media.giphy.com/media/wOtkVwroA6yzK/giphy.gif',
  'https://media.tenor.com/images/e0b46d664eecc78b09bfe36ccc7b1a04/tenor.gif'
]

exports.lewdP = [
  'https://cdn.discordapp.com/attachments/169950217007923201/366383509297692674/fa887d040806b095f58a5e51aafdc06dab4b69feb9497c27241d54263e9162f1_1.jpg',
  'http://i.imgur.com/5aEzsjo.gif',
  'http://avvesione.files.wordpress.com/2013/07/love_lab-01-natsuo-huggy-dakimakura-hug_pillow-kiss-saliva-comedy-embarrassing.jpg',
  'https://i.stack.imgur.com/MKMpFm.jpg',
  'http://i0.kym-cdn.com/photos/images/original/000/243/708/b73.png',
  'http://i0.kym-cdn.com/entries/icons/original/000/017/225/zAp2LzJ.jpg',
  'https://i.imgur.com/BAopHne.png',
  'https://i.imgur.com/Kscx9g5.png',
  'https://i.imgur.com/L0xyKWD.png',
  'http://i.imgur.com/RoWXWGK.png',
  'https://i.imgur.com/XoYgHyi.jpg',
  'http://i.imgur.com/pR018KF.png',
  'https://f4.bcbits.com/img/a0969478402_10.jpg',
  'http://i.imgur.com/PtHc5I4.jpg',
  'http://i.imgur.com/XybqQni.jpg',
  'http://images4.fanpop.com/image/photos/23400000/tama-chan-tamaki-suoh-23442506-500-317.gif',
  'http://31.media.tumblr.com/d956d395b73977ece03d48ce3d91f71a/tumblr_mwfp6ngGRg1slr9goo1_500.gif'
]

exports.slapP = [
  'https://68.media.tumblr.com/e7342896545dce3fe67137d35a1a1505/tumblr_npk0vvnC3R1qla6lro1_500.gif',
  'http://i.imgur.com/Kna2bLj.gif',
  'https://m.popkey.co/8aba9f/VWrYJ.gif',
  'https://media.giphy.com/media/jLeyZWgtwgr2U/giphy.gif',
  'https://media.giphy.com/media/Zau0yrl17uzdK/giphy.gif',
  'http://i.imgur.com/dzefPFL.gif',
  'https://media.giphy.com/media/oL7evncYvZ9II/giphy.gif',
  'https://media.tenor.com/images/85722c3e51d390e11a0493696f32fb69/tenor.gif',
  'https://media.giphy.com/media/LB1kIoSRFTC2Q/giphy.gif',
  'http://gifimage.net/wp-content/uploads/2017/07/anime-slap-gif-14.gif',
  'https://media.tenor.com/images/a6c2f17d9209f8f536b6b4bfbfb84686/tenor.gif',
  'https://media.tenor.com/images/cd54332b4f2456941c0362129681b1b6/tenor.gif',
  'http://gifimage.net/wp-content/uploads/2017/07/anime-slap-gif-9.gif',
  'https://media.giphy.com/media/L7iHfUrBk3cqY/giphy.gif',
  'https://media.tenor.com/images/1cf84bf514d2abd2810588caf7d9fd08/tenor.gif',
  'https://gifimage.net/wp-content/uploads/2017/07/anime-slap-gif-11.gif',
  'https://media.giphy.com/media/RdnJnbQ0lYGCQ/giphy.gif',
  'https://gifimage.net/wp-content/uploads/2017/07/anime-slap-gif-4.gif',
  'https://gifimage.net/wp-content/uploads/2017/07/anime-slap-gif-18.gif',
  'https://a.disquscdn.com/get?url=https%3A%2F%2F31.media.tumblr.com%2Fdd5d751f86002fd4a544dcef7a9763d6%2Ftumblr_inline_mya9hsvLZA1rbb2hd.gif&key=rO3ODUOrc2K-QUZIk2fDvw',
  'https://i2.wp.com/gifimage.net/wp-content/uploads/2017/07/anime-slap-gif-12.gif?fit=500%2C281&ssl=1',
  'http://gifimage.net/wp-content/uploads/2017/07/anime-slap-gif-8.gif',
  'http://i0.kym-cdn.com/photos/images/original/000/846/661/240.gif',
  'https://media.giphy.com/media/EpFsHUKK2MYvK/giphy.gif',
  'https://media.tenor.com/images/5401c0acac68ab8459b1c1d939a481fe/tenor.gif',
  'https://lh5.googleusercontent.com/-O2Zdez59tEQ/VNEATNFEX6I/AAAAAAAABHQ/rxDgE0hewu4/Slap.gif',
  'https://media.tenor.com/images/f42b4f2b7b6e69fc612b56b112a2e1e5/tenor.gif',
  'http://i.imgur.com/ObnxqQm.gif',
  'https://media.giphy.com/media/VEmm8ngZxwJ9K/giphy.gif',
  'https://media.tenor.com/images/0cff5692b5d7481067c0e449beb1bc1d/tenor.gif',
  'http://i0.kym-cdn.com/photos/images/newsfeed/000/940/326/086.gif',
  'http://i0.kym-cdn.com/photos/images/original/001/264/655/379.gif',
  'https://media.giphy.com/media/QrYsCBTHSIqfm/giphy.gif',
  'https://reallifeanime.files.wordpress.com/2014/06/akari-slap.gif',
  'https://s-media-cache-ak0.pinimg.com/originals/b8/f3/02/b8f302e2fa5f45fa4d472a23d828568b.jpg',
  'https://static.fjcdn.com/gifs/Bitch+slap+4+more+here+wwwyoutubecom+user+squabanime+and+here+thesquabnestcom+and+here+wwwfacebookcom+pages+squab+220040661488110+sk+timeline_161012_5187244.gif',
  'https://media.tenor.com/images/089b5fee602c2757f400ae44ae3f40f7/tenor.gif',
  'https://media.giphy.com/media/10Am8idu3qBYRy/giphy.gif',
  'https://media.tenor.com/images/1136f13fa88c72f7e57f386e04770d06/tenor.gif',
  'https://s-media-cache-ak0.pinimg.com/originals/4e/9e/a1/4e9ea150354ad3159339b202cbc6cad9.jpg',
  'https://media.giphy.com/media/1iw7RG8JbOmpq/giphy.gif',
  'https://media.tenor.com/images/00b874c763dd877638534bb55671dc59/tenor.gif',
  'http://gifimage.net/wp-content/uploads/2017/07/anime-slap-gif-20.gif',
  'https://38.media.tumblr.com/db2c23d95ea558373d5ac51a7b8b4193/tumblr_nl801msjXa1saml9ao2_500.gif',
]

exports.patP = [
  'https://78.media.tumblr.com/6bc4805da052bdeb34785a3acd59e69f/tumblr_olyfq6PNw01qbvovho1_500.gif',
  'https://78.media.tumblr.com/59074e59e5563e15623216e3e33cd259/tumblr_ojt62uIuDB1vztiw8o1_500.gif',
  'https://78.media.tumblr.com/1c433aeea03d0fcee34c22696ba1307b/tumblr_osl1kmMWL91qbvovho1_500.gif',
  'https://78.media.tumblr.com/71d93048022df065a1d2af96ab71afa3/tumblr_olykrec0DB1qbvovho1_500.gif',
  'https://78.media.tumblr.com/18e1fdcde34edf0cf03c588162fbd0ea/tumblr_npeccq4y3H1rzk6edo1_500.gif',
  'https://78.media.tumblr.com/5f971a365d815655803dcaea590df074/tumblr_od76a3qX4i1s9gdrpo1_500.gif',
  'https://78.media.tumblr.com/ee613e7778d2c7120e4a622f51b606da/tumblr_ov9bobF4qz1vfz661o1_500.gif',
  'https://78.media.tumblr.com/313a6fcdf842ba0e0f393de0746f6cd6/tumblr_oc9tu4rAff1v8ljjro1_500.gif',
  'https://m.popkey.co/a5cfaf/1x6lW.gif',
  'https://gifimage.net/wp-content/uploads/2017/07/head-pat-gif-21.gif',
  'https://media.giphy.com/media/ARSp9T7wwxNcs/giphy.gif',
  'http://i.imgur.com/laEy6LU.gif',
  'https://media.giphy.com/media/4HP0ddZnNVvKU/giphy.gif',
  'https://33.media.tumblr.com/cb4da84b16d8e189c5b7a61632a54953/tumblr_nrcwmt2SNG1r4vymlo1_400.gif',
  'https://funnypictures1.fjcdn.com/funny_gifs/Head_ac555b_6102763.gif',
  'https://78.media.tumblr.com/3b72bb8d292b80c37f8a6d64d2ff0cca/tumblr_o9ha9ez6pv1v7p6apo2_400.gif',
  'http://gifimage.net/wp-content/uploads/2017/07/head-pat-gif.gif',
  'http://gifimage.net/wp-content/uploads/2017/07/head-pat-gif-18.gif',
  'http://pa1.narvii.com/6444/4c7bd6014db28784b1dbaeb6eb9491cce4bbebb5_hq.gif',
  'http://i.imgur.com/LRDanyb.gif',
  'http://pa1.narvii.com/6375/2037371b0d018847c26326aa855b3ebcf5a22ec6_hq.gif',
  'https://s-media-cache-ak0.pinimg.com/originals/c0/3f/58/c03f5817acde4b1c168d31ffe02c522e.gif',
  'http://i2.kym-cdn.com/photos/images/original/001/142/787/396.gif',
  'https://animatedit.files.wordpress.com/2017/01/omake-gif-anime-gate-episode-15-tuka-head-pat.gif',
  'https://gifimage.net/wp-content/uploads/2017/07/head-pat-gif-16.gif',
  'https://media.tenor.com/images/fb3e0b0f18188450bfded4a585de2b90/tenor.gif',
  'http://data.whicdn.com/images/84233961/original.gif',
  'http://gifimage.net/wp-content/uploads/2017/07/head-pat-gif-5.gif',
  'http://funnypictures1.fjcdn.com/funny_gifs/Head_389b42_6102763.gif',
  'https://68.media.tumblr.com/5f971a365d815655803dcaea590df074/tumblr_od76a3qX4i1s9gdrpo1_500.gif',
  'http://31.media.tumblr.com/eeabfb1162d1976b9f4f6927f5e9639f/tumblr_mkt8lsn4En1rbyttso1_500.gif',
  'https://i.imgur.com/lZ4BP1C.gif',
  'https://68.media.tumblr.com/2d61aa2fd9286f5670fbb17b6e56475f/tumblr_o4ufimpBNt1tydz8to1_500.gif',
  'http://i.imgur.com/L8voKd1.gif',
  'http://gifimage.net/wp-content/uploads/2017/07/head-pat-gif-10.gif',
  'https://i.imgur.com/xXCmcJx.gif',
  'https://archive-media-0.nyafuu.org/c/image/1483/55/1483553008493.gif',
  'https://78.media.tumblr.com/b5b3aa9815fc4f367a90c6cebff82708/tumblr_om5f4tvcHX1thzx08o1_500.gif',
  'http://gifimage.net/wp-content/uploads/2017/07/head-pat-gif-20.gif',
  'https://media.giphy.com/media/104xeY1nIvrI64/giphy.gif',
  'http://i.imgur.com/CqGsABt.gif',
  'http://i3.kym-cdn.com/photos/images/original/000/915/038/7e9.gif',
  'https://thumbs.gfycat.com/ReflectingConfusedBluet-max-1mb.gif',
  'http://img24.laughinggif.com/pic/HTTP2xpdmVkb29yLmJsb2dpbWcuanAvZ2lmYW5pbWUvaW1ncy9kL2UvZGU1M2FiMWMuZ2lm.gif',
  'http://pa1.narvii.com/6260/9912a106df20e91d2681f7d0e3c8237c06586eab_hq.gif',
  'http://i.imgur.com/QmtaRmn.gif',
  'http://cloud-3.steamusercontent.com/ugc/93852834496370454/39194370AA7AC1056892B7F839643B24901F22BB/',
  'http://cdn-9chat-fun.9cache.com/media/photo/aoPO5LzVm_480wa_v1.gif',
  'http://49.media.tumblr.com/tumblr_lpbblk4UL21qbvovho1_500.gif',
  'https://i.warosu.org/data/tg/img/0486/06/1470269762425.gif',
  'http://pa1.narvii.com/6563/1c505849056037f244973a3be854c51c7a5c93f3_hq.gif'
]

exports.gropeP = [
  'https://media.giphy.com/media/3gDfReOhMWhd6/giphy.gif',
  'http://24.media.tumblr.com/10615c3d2f2818a3c34a6169b4b55a0c/tumblr_mgfir2MBiA1rk6j3co1_500.gif',
  'https://i.imgur.com/7hjrBpm.gif',
  'http://pa1.narvii.com/5700/26dc7460ae73597a9193001d1cdf620754bf02c9_hq.gif',
  'http://static.fjcdn.com/gifs/Water_3e65d2_1424780.gif',
  'http://pa1.narvii.com/5938/11933a4215ffe08a75bd643da4e6d4a466f99c42_hq.gif',
  'http://pa1.narvii.com/6412/cc1fdecad374e0d7af851c46dae4554beb76ba54_hq.gif',
  'http://pa1.narvii.com/6094/0c6e79490edededcfc4f6ba40a5f836b0b242865_hq.gif',
  'http://pa1.narvii.com/6094/6408ab1c0580c07bbdfe19b4edc7d46b1bdfdfab_hq.gif',
  'http://i.imgur.com/SlQSPla.gif',
  'https://ci.memecdn.com/5980420.gif',
  'https://media.giphy.com/media/s5lQ1ARYeOCdO/giphy.gif',
  'http://i.imgur.com/zYWISM3.gif',
  'http://25.media.tumblr.com/tumblr_mcj8lwHuUj1rv36muo1_400.gif',
  'https://media.giphy.com/media/TGbGDLKchKF56/giphy.gif',
  'https://media.giphy.com/media/JdhGTJSn0YMFi/giphy.gif',
  'http://cloud-3.steamusercontent.com/ugc/710786427737334267/30E3EEB8D90C6BB130C2499686AC7A65AE7C0DE0/',
  'http://pa1.narvii.com/5718/527486e7a1894f00d39443481d3d20cf2b123d34_hq.gif',
  'http://rs867.pbsrc.com/albums/ab233/BSM-Capulet/Animated%20Gifs%20and%20Anime/Himegrope.gif~c200',
  'http://pa1.narvii.com/5711/02fb51d8854855e1e14bc7a5e0ba84d28da160f1_hq.gif',
  'http://i0.kym-cdn.com/photos/images/original/000/965/466/bb1.gif',
  'https://vignette4.wikia.nocookie.net/dogs-of-war/images/e/e8/C4ss.gif/revision/latest?cb=20160507211813',
  'https://static.fjcdn.com/gifs/Mango_19a43d_5515757.gif',
  'https://s-media-cache-ak0.pinimg.com/originals/85/e8/0d/85e80de11d761c931553ce04b4223ce7.gif',
  'http://24.media.tumblr.com/002a9723796cfa232522ddab80943143/tumblr_mnqlxmWh5G1s9nzk7o1_500.gif',
  'https://i.warosu.org/data/cgl/img/0085/60/1440092303236.gif'
]

exports.disgustP = [
  'http://images5.fanpop.com/image/answers/2454000/2454603_1329760918765.95res_499_281.jpg',
  'http://www.entravity.com/wp-content/uploads/2013/10/kyoukai-3-19-mitsuki-look-of-disgust.jpg',
  'http://i.imgur.com/YV3oSUV.jpg',
  'https://myanimelist.cdn-dena.com/s/common/uploaded_files/1482990867-a74ffd8e39cd319b49035ba397a08c41.jpeg',
  'http://i0.kym-cdn.com/photos/images/facebook/000/069/019/Excalibur_face_1.PNG',
  'https://phelan.files.wordpress.com/2008/10/kan4_title.jpg',
  'https://img.fireden.net/a/image/1446/03/1446035988583.png',
  'https://i.imgur.com/PMJ1V2Q.jpg',
  'https://static2.fjcdn.com/comments/I+actually+legit+wanted+to+puke+right+when+they+got+_cbc2ba03fa31bdfac47c9bd6afdcd066.png',
  'http://i.imgur.com/26Jtecd.jpg',
  'http://i.imgur.com/plGxQqL.gif'
]

//clocks for time command
exports.clocks = ['🕛', '🕐', '🕑', '🕒', '🕓', '🕔', '🕕', '🕖', '🕗', '🕘', '🕙', '🕚']

exports.memeSubreddits = [
  'memes',
  'DeepFriedMemes',
  'bonehurtingjuice',
  'surrealmemes',
  'dankmemes',
  'meirl',
  'me_irl',
  'funny'
]

exports.hentaiSubreddits = [
  'hentai',
  'hentiny',
  'ecchi',
  'rule34',
  'HENTAI_GIF',
  'thick_hentai'
]

exports.nsfwSubreddits = [
  'nsfw',
  'HighResNSFW',
  'porn',
  'BonerMaterial',
  'adorableporn',
  'juicyasians',
  'LegalTeens',
  'nsfwcosplay'
]

exports.nsfwGifSubreddits = [
  'NSFW_GIF',
  'nsfw_gifs',
  'porninfifteenseconds',
  '60FPSPorn',
  'porn_gifs',
  'nsfw_Best_Porn_Gif',
  'LipsThatGrip'
]

exports.nsfwError = [
  'G-gya! This isn\'t an NSFW channel!',
  'This doesn\'t seem to be an NSFW channel...',
  "I'm sorry! But this stuff belongs in NSFW channels!",
  'That belongs in NSFW channels!', 
  "I can't post this here! Please direct me to an NSFW channel!",
  "I\'m afraid that kind of stuff isn't allowed in here..",
  "This doesn't look like an NSFW channel!",
  "Please try again in an NSFW channel!",
  "u///u, I don't think I can post that in your average channel.",
  "Don't make me post that here...",
  "💢That doesn't belong here!",
  "W-What? I can't post that here!"
]

exports.rightThere = [
  '🔊🔊🚨🚨WARNING🔊🚨🚨WARNING🚨🚨🔊THIS IS A 🐸DANK 👽MEME❗❗ 🐸ALERT. INCOMING 🐸DANK 👽MEME🐸 👐👌HEADING STRAIGHT 🚀🚀YOUR WAY. 🔜👆👆👆PLEASE TAKE ANY PRECAUTIONS🚧🚧 NECESSARY TO PREPARE YOURSELF FOR THIS 🐸DANK 👽MEME❗❗ 🐸 🌋🌋🌋 .BUCKLE UP♿♿♿ THEM SEATBELTS👮👮,PUT THEM CELLPHONES ON SILENT📵📵 AND LOOSEN THAT ANUS👅👅🍑🍑🍑🍩🍩💩💩 CUZ THIS MEME JUST CAME STRAIGHT OUT OF THE 🚬🚬 🍁🏭🍁🏭🍁🚬🚬DANK FACTORY.',
  '✋✋✋✋✋hol\' up hol\' up ✋✋ looks 👀 like we got a master 🎓 memer 🐸🐸🐸 over here 👈👈👈👩🏼👩🏼hold on to your 👙panties👙ladies!💋💁fuccbois better back the hell ⬆️up⬆️ this absolute 🙀🙀🙀 maaaaaadman!!1! 👹 all you other aspiring 🌽🌽 memers👽👻💀 mmmight as wwwell give up! 👎👎👎👎cuse 👉this guy👈is as good 👌👌👌as it gets! 👏👏👏😹😹',
  '💀💀💀💀🎺🎺🎺NOW WATCH ME SPOOK💀💀💀NOW WATCH ME DOOT DOOT🎺🎺🎺🎺NOW WATCH ME SPOOK SPOOK💀💀💀💀💀🎺🎺🎺🎺WATCH ME DOOT DOOT💀🎺🎺💀🎺💀🎺🎺💀',
  'Get dunked, m8 💯💯 You jUSt goT🏀🏀🏀r👌👌oasted🏀🏀🏀💯💯💯Dunked👌👌gEt🏀💯💯👌👌👀👀👀🔥🔥sAvaGe✔✔👌👌👌💯💯💯🔥🔥🏀🏀🏀🏀✔✔✔👀👀👀ggeettttt dUNNKkeDdd oNnn!!👌👌gET it🏀🏀YouRe goNNa haVe a Bad👎👎👎👎👎tim🕐🕐e he✔✔Re🏀🏀👌👌👌🏀💯💯gEt dUNked❌👍👍so sa🔥🔥vaGe he rekt❌❌himself﻿',
  '💯💯hOHoHOHHHHMY GOFD 😂😂😂 DUDE 👌i AM 👉LITERALLY👈 iN 😂TEARS😂 RIGHT NOW BRo 👆👇👉👈 hHAHAHAHAHAHAHA ✌️👌👍 TAHT WA SOO FUNNY DUd 💧💧😅😂💦💧I cAN NOT BELIEV how 💯FUNny 👌👍💯thta shit wa s 👀👍😆😂😂😅 I 👦 CAN NOT ❌ bRATHE 👃👄👃👄❌❌ / HELP ❗️I NEEd 👉👉 AN a m b u l a n c e🚑🚑 SSSooOOoo00000oOOOOOøøøØØØØØ FUNY ✔️☑️💯💯1️⃣0️⃣0️⃣😆😆😂😂😅 shit man ❕💯💯🔥☝️👌damn',
  'OMG 😱😱😱 BRO👬 CALM 😴😴 DOWN BRO ⬇️⬇️ SIMMER ☕️☕️ DOWN⬇️⬇️ U WANNA KNOW Y⁉️ BC 💁💁 IT WAS JUST A PRANK 😂😂😂 😛😜 HAHAHA GOT U 👌👌 U FUKIN RETARD 😂😁😁THERE\'S A CAMERA 📹📷 RIGHT OVER 👈👇👆☝️ THERE 📍U FAGOT 👨‍❤️‍💋‍👨👨‍❤️‍💋‍👨👐WE 👨‍👨‍👦 GOT U BRO👬. I BET U DIDNT 🙅🙅NOE 💆HOW 2⃣ REACT WHEN MY 🙋 BRO DESMOND 😎😎 CAME UP ⬆️ TO U AND 💦💦😫😫 JIZZED ALL OVER UR 👖👖 SWEET JEANS 😂😂 IT WAS SO FUNNY 😂😛😀😀😅 NOW U HAVE 🙋👅👅 SUM BABY👶👶 GRAVY 💦🍲 ALL OVER THEM SHITS😵😵IT\'S JUST A PRANK BRUH',
  '👌👀👌👀👌👀👌👀👌👀 good shit go౦ԁ sHit👌 thats ✔ some good👌👌shit right👌👌th 👌 ere👌👌👌 right✔there ✔✔if i do ƽaү so my selｆ 💯 i say so 💯 thats what im talking about right there right there (chorus: ʳᶦᵍʰᵗ ᵗʰᵉʳᵉ) mMMMMᎷМ💯 👌👌 👌НO0ОଠＯOOＯOОଠଠOoooᵒᵒᵒᵒᵒᵒᵒᵒᵒ👌 👌👌 👌 💯 👌 👀 👀 👀 👌👌Good shit',
  '👎👀👎👀👎👀👎👀👎👀  bad shit ba̷̶ ԁ sHit 👎 thats ❌ some bad 👎👎shit right 👎👎 th   👎 ere 👎👎👎 right ❌ there ❌ ❌ if i do ƽaү so my selｆ🚫 i say so 🚫 thats not what im talking about right there right there (chorus: ʳᶦᵍʰᵗ ᵗʰᵉʳᵉ) mMMMMᎷМ 🚫 👎 👎👎НO0ОଠＯOOＯOОଠଠOoooᵒᵒᵒᵒᵒᵒᵒᵒᵒ 👎 👎👎 👎 🚫 👎 👀 👀 👀 👎👎Bad shit',
  '👌👽👌👽👌👽 ayy lmao ayyy lmao lmao👌 thats ✔ some ayyy👌👌lamayo right👌👌there👌👌👌 right✔there ✔✔if i do LMAO so my self 💯 i ayyy so 💯 thats what im probing about right there right there (chorus: ʳᶦᵍʰᵗ ᵗʰᵉʳᵉ) mMMMMᎷМ💯 👌👌 👌AAAYYYYyyyyYYYYYyyyyyyʸʸʸʸʸʸʸʸ👌 👌👌 👌 💯 👌 👽👽👽👌👌ayy lmao',
  '💣🕛💣🕜💣🕝💣🕞💣👀🕙🕑 bomb clock boMb cLock💣 thats ⏰ a🕛 bomb ass 🕑💣⏰clock right💣💣there🕞💣🕙 right⏰there 💣💣i built it my self 👳 i built it 👳 thats what im talking about right there right there (chorus: ʳᶦᵍʰᵗ ᵗʰᵉʳᵉ) mMMMMᎷМ👳 💣🕞 💣НO0ОଠOOOOOОଠଠOoooᵒᵒᵒᵒᵒᵒᵒᵒᵒ🕑💣⏰⏰ 💣 👳 💣 👀⏰🕙🕐 💣💣Bomb clock',
  '💩🐃💩🐃💩🐃💩🐃💩🐃 bull shit bull sHit💩 thats ✖️ some bull💩💩shit right💩💩th 💩 ere💩💩💩 right✖️there ✖️✖️if i do ƽaү so my selｆ ‼️ i say so ‼️ thats what im talking about right there right there (chorus: ʳᶦᵍʰᵗ ᵗʰᵉʳᵉ) mMMMMᎷМ‼️ 💩💩 💩HO0ОଠＯOOＯOОଠଠOoooᵒᵒᵒᵒᵒᵒᵒᵒᵒ💩 💩💩 💩 ‼️ 💩 🐃 🐃 🐃 💩💩Bull shit',
  '✈🏢✈🏢✈🏢✈🏢✈🏢 bush did 9/11✈ bush ✔ did it✈🏢blew up✈🏢the towers✈🏢🏢🌏 the✔towers ✔✔if i do ƽaү so my self 👀 watch loose change 👀 how did tower seven collapse tower seven tower seven (chorus: ᵗᵒʷᵉʳ ˢᵉᵛᵉᶰ) mMMMMᎷМ🌏 👌👌 👌НO0ОଠOOOOOОଠଠOoooᵒᵒᵒᵒᵒᵒᵒᵒᵒ👌 👌👌 👌 🌏 ✈ 🏢 🏢 👀 👌👌bush did it',
  '🍕🍅🍕🍅🍕🍅🍕🍅🍕🍅 cheesy shit cheesy sHit🍕 thats ✔ some cheesy🍕🍕shit right🍕🍕th 🍕 ere🍕🍕🍕 right✔there ✔✔if i do ƽaү so my selｆ 🍴 i say so 🍴 thats what im talking about right there right there (chorus: ʳᶦᵍʰᵗ ᵗʰᵉʳᵉ) mMMMMᎷМ🍴 🍕🍕 🍕НO0ОଠＯOOＯOОଠଠOoooᵒᵒᵒᵒᵒᵒᵒᵒᵒ🍕 🍕🍕 🍕 🍴 🍕 🍅🍅🍅 🍕🍕Cheesy shit',
  '🎃👻🎃👻🎃👻👻👻🎃👻 spooky shit spooky sHit🎃 thats ✔ some spooky🎃🎃shit right🎃🎃th 🎃 ere🎃🎃🎃 right✔there ✔✔if i do ƽaү so my selｆ 💯 i say so 💯 thats what im talking about right there right there (chorus: ʳᶦᵍʰᵗ ᵗʰᵉʳᵉ) mMMMMᎷМ💯 🎃🎃 🎃BO0ОଠＯOOＯOОଠଠOoooᵒᵒᵒᵒᵒᵒᵒᵒᵒ🎃 🎃 🎃 🎃 💯 🎃 👻👻 👻 🎃🎃spooky shit',
  '❤️😍❤️😍❤️😍❤️😍❤️ m\'lady shit m\'lady sHit❤️ thats ✔ some m\'lady 😍😍shit right❤️❤️there😍😍😍 right✔there ✔✔if i do ƽaү so my self 🙇 i say so 🙇 thats what im talking about right there right there (chorus: ʳᶦᵍʰᵗ ᵗʰᵉʳᵉ) mMMMMᎷМ🙇 😍😍😍НO0ОଠOOOOOОଠଠOoooᵒᵒᵒᵒᵒᵒᵒᵒᵒ😍😍😍😍 🙇 😍 ❤️ ❤️ ❤️ 😍 ❤️ M\'lady shit',
  '💉🔪 💉🔪💉🔪edgy shit edgY sHit 🔪thats 🔫some edgy💉💉 shit right 🔪th🔪 ere💉💉💉 right there 🚬🚬if i do ƽaү so my selｆ 🔫i say so 🔫 thats what im talking about right there right there (chorus: ʳᶦᵍʰᵗ ᵗʰᵉʳᵉ) mMMMMᎷМ🔫 🔪🔪🔪НO0ОଠＯOOＯOОଠଠOoooᵒᵒᵒᵒᵒᵒᵒᵒᵒ🔪🔪🔪 🔫 💉💉 🔪🔪 Edgy shit',
  '👴📅👴📅👴📅👴📅👴📅 old shit 0ld sHit👴 thats 💾 some old👴👴shit right👴👴th 👴 ere👴👴👴 right💾there 💾💾if i do ƽaү so my selｆ 🕙 i say so 🕥 thats what im talking about right there right there (chorus: ʳᶦᵍʰᵗ ᵗʰᵉʳᵉ) mMMMMᎷМ🕔 👴👴 👴НO0ОଠＯOOＯOОଠଠOoooᵒᵒᵒᵒᵒᵒᵒᵒᵒ👴 👴👴 👴 🕣 👴 📅 📅 📅 👴👴Old shit',
  '🐸♊️🐸♊️🐸♊️🐸♊️🐸♊️ good memes go౦ԁ mEmes🐸 thats 🔫🔫some good🐸🐸memes right🐸🐸th 🐸 ere🐸🐸🐸 right🔫there 🔫🔫if i do ƽaү so my selｆ ❓❗️👟👟❓❗️ i say so ❓❗️👟👟❓❗️ thats what im talking about right there right there (chorus: ʳᶦᵍʰᵗ ᵗʰᵉʳᵉ) mMMMMᎷМ❓❗️👟👟❓❗️ 🐸🐸 🐸НO0ОଠＯOOＯOОଠଠOoooᵒᵒᵒᵒᵒᵒᵒᵒᵒ🐸 🐸🐸 🐸 ❓❗️👟👟❓❗️ 🐸 ♊️ ♊️ ♊️🐸🐸Good memes',
  '💀🎺💀🎺💀🎺💀🎺💀🎺 gooD boNes n calcium💀 thank 🎺 mr skeltal g💀💀ood bones💀💀and calc💀 ium💀💀💀 good bones🎺and calcium 🎺🎺if i dootƽaү thank skeltal man 🎶 doot doot doot doot🎶 good bones n calcium good bones (chorus: ᵈᵒᵒᵗ ᵈᵒᵒᵗ) mMMMMᎷМ🎶 💀💀💀DO0ОଠＯOOＯOОଠଠOoooᵒᵒᵒᵒᵒᵒᵒᵒᵒT💀 💀 💀💀 🎶 💀 🎺 🎺 🎺 💀💀thank mr skeltal',
  '✌🔪✌🔪✌🔪✌🔪✌🔪 cheeky shyte cheEky sHyte✌ thats ✖ sum cheeky✌✌shyte rite✌✌there✌✌✌ rite✖there ✖✖if i do ƽay so meself 🔨 i say so 🔨 ill bring me cru shag ur nans rusty cunt (chorus: ᶰ ᵘʳ ˢᶦˢ) mMMMMᎷМ🔨 ✌✌✌HO0ОଠOOOOOОଠଠOoooᵒᵒᵒᵒᵒᵒᵒᵒᵒ✌ ✌ ✌ ✌ 🔨 ✌ 🔪 🔪 🔪 ✌✌Cheeky shyte',
  '🍝👀🍝👀🍝👀🍝👀 good pasta gOod pASTA 🍝 thats 🍴 some good 🍝 🍝 pasta right 🍝 🍝 there 🍝 🍝 🍝 right🍴there 🍴 🍴If I do say so myself 💯 I say so 💯 that\'s what I\'m talking about right there right there (chorus: ʳᶦᵍʰᵗ ᵗʰᵉʳᵉ) mMMMMMM 💯 🍝 🍝 🍝 HO0OoOOOOOOoOoooooooooooo 🍝 🍝 🍝 🍝 💯 🍝 👀 👀 👀 🍝 🍝 good pasta',
  '😩💦😩💦😩💦😩💦😩💦 sexy shit sexy sHit😩 thats 🐔 some sexy😩👅shit right😩th 😩 ere😩👅😩 right🐔there 🐔🐔if i do ƽaү so my selｆ ✊ i say so ✊ thats what im talking about right there right there (chorus: ʳᶦᵍʰᵗ ᵗʰᵉʳᵉ) mMMMMᎷМ✊ 😩👅😩НO0ОଠＯOOＯOОଠଠOoooᵒᵒᵒᵒᵒᵒᵒᵒᵒ😩 😩👅 😩 ✊ 😩 💦💦 💦 😩👅Sexy shit',
  '🚫🚫🚫🚫🚫💰💰💰socialist shit socialist sHit thats ✔ some socialist🚫🚫shit right💰💰th 🚫 ere💰💰💰 right✔there ✔✔if i do ƽaү so my selｆ 💯 i say so 💯 thats what im talking about right there right there (chorus: ʳᶦᵍʰᵗ ᵗʰᵉʳᵉ) mMMMMᎷМ💯☭☭☭НO0ОଠＯOOＯOОଠଠOoooᵒᵒᵒᵒᵒᵒᵒᵒᵒ🚫🚫🚫🚫🚫 💯 💰💰💰💰socialist shit',
  '🍗🍷🍗🍷🍗🍷🍗🍷🍗🍷thankful shit thAnkFul sHit🍛 🍛thats ✔ some ThaNkful👨‍👨‍👦🍁shit right📺👩‍👩‍👦th 🌽 ere👪🏈📺 right✔there ✔✔if i do gobble so my selｆ 💯 i say so 💯 🍗🌽thats what im talking about right there right there (chorus: ʳᶦᵍʰᵗ ᵗʰᵉʳᵉ) mMMMMᎷМ💯 🏈🍷🍷НO0ОଠＯOOＯOОଠଠOoooᵒᵒᵒᵒᵒᵒᵒᵒᵒ👪📺🍗🍗💯 👩‍👩‍👦🏈🍂🍷🍷 🌽 👨‍👨‍👦Tha nkful shit',
  '👌🐶👌🐶👌🐶👌🐶 good dog go౦ԁ dOg👌 thats ✔ a gOOd 🐶 🐶 dog right 🐕 🐕 there👌👌👌 right🐶there ✔✔if i do ƽaү so my self 💯 i say so 💯 thats what im talking about right there right there (chorus: ʳᶦᵍʰᵗ ᵗʰᵉʳᵉ) mMMMMᎷМ💯 👌👌 👌НO0ОଠOOOOOОଠଠOoooᵒᵒᵒᵒᵒᵒᵒᵒᵒ👌 🐕 🐕 👌 💯 👌 🐶 🐶 🐶 👌👌Good dog',
  '🍤🍤👀🍤👀🍤👀🍤👀🍤👀 good shrimp go౦ԁ shrimp🍤 thats 🍤 some good🍤🍤 shirmp right🍤🍤there 🍤🍤🍤 right✔there ✔✔if i do ƽaү so my self 💯 i say so 💯 thats what im talking about right there red lobster quality shrimp (chorus: ʳᶦᵍʰᵗ ᵗʰᵉʳᵉ) mMMMMᎷМ💯 🍤🍤🍤НO0ОଠOOOOOОଠଠOoooᵒᵒᵒᵒᵒᵒᵒᵒᵒ🍤 🍤 🍤 🍤 💯 🍤 👀 👀 👀 🍤🍤Good shrimp',
  '🙏👀🙏👀🙏👀🙏👀 holy shit hoLy sHit 🙏 thats 😇 some holy 🙏 🙏 shit right 🙏 🙏 th 🙏 ere 🙏 🙏 🙏right 😇 there 😇 😇 if i do say so my sel f 👼 i say so 👼 thats what im praying about right there right (chorus: ʳᶦᵍʰᵗ ᵗʰᵉʳᵉ) mMMMMMM 👼 🙏 🙏 🙏 HOOOO0OOO OO O OOooooooooooo 🙏 🙏🙏 🙏 👼 🙏 👀👀👀👀 🙏 🙏 Holy shit',
  '🐱👌 🐱👌🐱👌🐱👌🐱👌 good cats go౦ԁ cAts👌 thats 🐈 some good👌👌cats right👌👌th 🐈 ere 🐱 🐱 🐱 right 🐈 there 🐈 🐈 if i do ƽaү so my selｆ 💯 i say so 💯 thats what im talking about right there right there (chorus: ʳᶦᵍʰᵗ ᵗʰᵉʳᵉ) mMMMMᎷМ💯 🐱 🐱 🐱 НO0ОଠＯOOＯOОଠଠOoooᵒᵒᵒᵒᵒᵒᵒᵒᵒ👌 👌👌 👌 💯 👌 🐈 🐈 🐈 👌👌Good cat',
  '🎁🎄🎅🎁🎄🎅🎁🎄🎅Christmas shit Christmas sHit🎅thats 🎊some Christmas🎊🎊shit right🎅🎁🎄th 🎅ere🎁🎄🎅 right🎊there 🎅🎁if i do ƽaү so my selｆ 🎊 i say so 🎊thats what im talking about right there right there (chorus: ʳᶦᵍʰᵗ ᵗʰᵉʳᵉ) mMMMMᎷМ🎊 🎁🎅🎄НO0ОଠＯOOＯOОଠଠOoooᵒᵒᵒᵒᵒᵒᵒᵒᵒ 🎅🎁🎄🎅🎊 🎅 🎁🎄🎊🎅Christmas shit',
  '👠👡👠👡👠👡👠👡👠👡 nice shoes niCe sHoes👠 thats 👢 some nice👠👠shoes right👠👠there👠👠👠 right👢there 👢👢if i ƽaү so my self 👟 i say so 👟 thats what im texting about right now right now (chorus: ʳᶦᵍʰᵗ ᶰᵒʷ) oOOOOᎷO👟 👠👠 👠OO0ОଠOOOOOОଠଠOoooᵒᵒᵒᵒᵒᵒᵒᵒᵒ👠 👠👠 👠 💯 👠 👡👡👡 👠👠Nice shoes',
  '💀🌞💀🌞💀🌞💀🌞💀🌞 dark souls daRk sOUls💀 thats 🔥 some dark💀💀souls right💀💀there💀💀💀 right🔥there 🔥🔥if i do ƽaү so my self 🔥 i say so 🔥 thats what im talking about right there right there (chorus: ᵍʷʸᶰ ᶫᵒʳᵈ ᵒᶠ ᶜᶦᶰᵈᵉʳ) mMMMMᎷМ🔥 💀💀💀💀 🌞🌞🌞💀💀Dark souls',
  '🚹 🏀 🚹 🏀 🚹🏀 🚹 🏀 🚹 🏀 bro shit br౦ sHit 🚹thats 🎮 some bro🚹 🚹shit right 🚹th 🚹 ere 🚹 🚹 🚹 right🎮there 🎮🎮if i do ƽaү so my selｆ 🏆 i say so 🏆thats what im talking about right there right there (chorus: ʳᶦᵍʰᵗ ᵗʰᵉʳᵉ) mMMMMᎷМ🏆🚹 🚹 🚹НO0ОଠＯOOＯOОଠଠOoooᵒᵒᵒᵒᵒᵒᵒᵒᵒ 🚹 🚹 🚹 🚹🏆 🚹 🏀 🏀 🏀 🚹 🚹Bro shit',
  '😴💤😴💤😴💤😴💤😴💤 tired shit tiręd sHit😴 thats ✔ some tired 😴😴shit right😴😴th 😴 ere😴😴😴 right✔there ✔✔if i do ƽaү so my selｆ 🌑 i say so 🌑 thats what im talking about right there right there (chorus: ʳᶦᵍʰᵗ ᵗʰᵉʳᵉ) mMMMMᎷМ🌑 😴😴 😴YaaaaAAAaaWWWwWWwwwnnNNnnNnn😴😴😴😴 🌑 😴 💤💤💤 😴😴Tired shit',
  '💥🔫💥🔫💥🔫💥🔫💥🔫gun shit gun sHit🔫 thats 🔫some gun🔫🔫shit right🔫🔫th 💥 ere🔫🔫🔫right💥there 🔫🔫if i do ƽaү so my selｆ 🔪 i say so 🔪thats what im talking about right there right there (chorus: ʳᶦᵍʰᵗ ᵗʰᵉʳᵉ) mMMMMᎷМ🔪 🔫🔫НO0ОଠＯOOＯOОଠଠOoooᵒᵒᵒᵒᵒᵒᵒᵒᵒ🔫🔫🔫🔫 🔪💥💥🔫🔫Gun shit',
  '🎀👀🎀👀💞👀🎀👀✨👀 kawaii shit kawaii sHit👌 thats ✔ some sugoi👌💕shit right🌟👌th 💓 ere👌✨👌 right✔there ✔✔if watashi do ƽaү so my selｆ 💯 watashi say so 💯 thats what boku wa talking about right there right there (chorus: ʳᶦᵍʰᵗ ᵗʰᵉʳᵉ) mMMMMᎷМ💯 👌👌 🐱НO0ОଠＯOOＯOОଠଠOoooᵒᵒᵒᵒᵒᵒᵒᵒᵒ👌 👌🎀👌 💯 👌 👀 👀 👀 🎀👌moe shit',
  '🐺🐯🐯🐯🐺🐯 🐺🐯🐺🐯 furry shit furry sHit🐺 thats 🐲some furry🐺 🐺shit right🐺 🐺th🐺 ere🐺🐺🐺 right🐲there 🐲🐲if i do ƽaү so my selｆ 🐾 i say so 🐾 thats what im talking about right there right there (chorus: ʳᶦᵍʰᵗ ᵗʰᵉʳᵉ) mMMMMᎷМ🐾 🐺🐺🐺🐺НO0ОଠＯOOＯOОଠଠOoooᵒᵒᵒᵒᵒᵒᵒᵒᵒ🐺 🐺🐺🐺 🐾 🐺 🐯 🐯 🐯 🐺🐺Furry shit',
  '🌌🌙🌌🌙🌌🌙🌌🌙🌌🌙 space shit spACe sHit🌌 thats ✔ some space🌌🌌shit right🌌🌌th 🌌 ere🌌🌌🌌 right✔there ✔✔if i do ƽaү so my selｆ 💯 i say so 💯 thats what im talking about right there right there (chorus: ʳᶦᵍʰᵗ ᵗʰᵉʳᵉ) mMMMMᎷМ💯 🌌🌌 🌌НO0ОଠＯOOＯOОଠଠOoooᵒᵒᵒᵒᵒᵒᵒᵒᵒ🌌 🌌🌌 🌌 💯 🌌 🌙 🌙 🌙 🌌🌌Space shit',
  '🐣💕🐣💕🐣💕🐣💕🐣💕 cute shit cute sHit💕 thats 💖some cute💕💕shit right💕💕th 💕 ere💕💕💕right💖there 💖💖if i do ƽaү so my selｆ 💋 i say so 💋 thats what im talking about right there right there (chorus: ʳᶦᵍʰᵗ ᵗʰᵉʳᵉ) mMMMMᎷМ💋 💕💕💕НO0ОଠＯOOＯOОଠଠOoooᵒᵒᵒᵒᵒᵒᵒᵒ💕💕💕 💋 💕 🐣🐣🐣💕💕Cute shit',
  '🔍 👀🔍 👀🔍 👀🔍 👀🔍 👀 dramatic shit dramati© sHit👌 thats 😒 some dramatic🔍🔍shit right🔍🔍th 🔍 ere🔍🔍🔍 right😒 there 😒 😒 if i do ƽaү so my selｆ 😓 i say so 😓 thats what im talking about right there right there (chorus: ʳᶦᵍʰᵗ ᵗʰᵉʳᵉ) mMMMMᎷМ😓 🔍🔍 🔍НO0ОଠＯOOＯOОଠଠOoooᵒᵒᵒᵒᵒᵒᵒᵒᵒ🔍 🔍🔍 🔍😓 🔍 👀 👀 👀 🔍🔍Dramatic shit',
  '🌿🌿🌿🌿🌿🌿🌿🌿🌿🌿dank shit dank sHit🌿thats ✔ some dank🌿🌿shit right🌿🌿th 🌿ere🌿🌿🌿right✔there ✔✔if i do ƽaү so my selｆ 🚬i say so 🚬thats what im talking about right there right there (chorus: ʳᶦᵍʰᵗ ᵗʰᵉʳᵉ) mMMMMᎷМ🚬🌿🌿🌿НO0ОଠＯOOＯOОଠଠOoooᵒᵒᵒᵒᵒᵒᵒᵒᵒ🌿🌿🌿🌿 🚬 🌿👀 👀 👀 🌿🌿Dank shit',
  '📟💾📟💾📟💾📟💾📟💾 90s shit 90s sHit📟 thats ✔ some 90s📟📟shit right📟📟there📟📟📟 right✔there ✔✔if i do ƽaү so my self 💯 i say so 💯 thats what im talking about right there right there (chorus: ʳᶦᵍʰᵗ ᵗʰᵉʳᵉ) mMMMMᎷМ💯 📟📟 📟НO0ОଠOOOOOОଠଠOoooᵒᵒᵒᵒᵒᵒᵒᵒᵒ📟 📟📟 📟 💯 📟 💾💾💾 📟📟90s shit',
  '⛵👭⛵👬⛵👫⛵👭⛵👬 good ship ba̷̶ ԁ sHit ⛵ thats 💖 some good ⛵⛵ship right ⛵⛵ th ⛵ ere ⛵⛵⛵ right 💖 there 💖 💖 if i do ƽaү so my selｆ👫 i say so 💖 thats not what im talking about right there right there (chorus: ʳᶦᵍʰᵗ ᵗʰᵉʳᵉ) mMMMMᎷМ 👭 ⛵ ⛵⛵НO0ОଠＯOOＯOОଠଠOoooᵒᵒᵒᵒᵒᵒᵒᵒᵒ ⛵ ⛵⛵ ⛵ 👬 ⛵ 👀 👀 👀 ⛵⛵Good ship',
  '🍔🍟🍔🍟🍔🍟🍔 yummy shit yummy sHit🍔 thats 🍟 some yummy🍔🍔shit right🍔🍟th 🍟 ere🍟🍔🍟 right🍟there 🍟🍔if i do ƽaү so my selｆ 🍟 i say so 🍔 thats what im talking about right there right there (chorus : ʳᶦᵍʰᵗ ᵗʰᵉʳᵉ) mMMMMᎷМ🍟🍔 🍟🍟🍔НO0ОଠＯOOＯOОଠଠOoooᵒᵒᵒᵒᵒᵒᵒᵒᵒ🍟🍔🍟🍔🍔🍟🍔🍟yummy shit',
  '💧⚡️💧⚡️💧⚡️💧⚡️💧stormy shit stOrmy sHit⚡️thats ☁️ some stormy⚡️⚡️shit right⚡️⚡️th ⚡️ ere⚡️⚡️⚡️ right☁️there ☁️☁️if i do ƽaү so my selｆ ☔️ i say so ☔️ thats what im talking about right there right there (chorus: ʳᶦᵍʰᵗ ᵗʰᵉʳᵉ) mMMMMᎷМ☔️ ⚡️⚡️ ⚡️НO0ОଠＯOOＯOОଠଠOoooᵒᵒᵒᵒᵒᵒᵒᵒᵒ⚡️ ⚡️⚡️ ⚡️ ☔️ ⚡️ 💧💧💧 ⚡️⚡️Stormy shit',
  '🎂👀🎂👀🎂👀🎂👀 birthday shit bday shit 🎂 thats 🎁 some birth🎂🎂 shit right 🎂🎂 th🎂here🎂🎂🎂 right 🎁 there 🎁🎁 if i do ƽaү so my selｆ🏫 i say so 🏫 thats what im talking about right there right there (chorus: ʳᶦᵍʰᵗ ᵗʰᵉʳᵉ) mMMMMᎷМ 🏫 🎂🎂🎂НO0ОଠＯOOＯOОଠଠOoooᵒᵒᵒᵒᵒᵒᵒᵒᵒ 🎂🎂🎂🎂🏫🎂👀👀🎂🎂 birthday shit',
  '👼🙏👼🙏👼🙏👼🙏👀👼👼 pope shit poPe shit 👼 thats 🙏 some ⛪ pope ass 🙏👼💒 shit right ⛪⛪ there 👼💒🙏 right 🙏 there 👼👼 if i do preach so myƽelf ⛪ i say so 👌 thats what my sermon is about right there right there (choir: ʳᶦᵍʰᵗ ᵗʰᵉʳᵉ) mMMMMᎷМ 🙏👼💒 НO0ОଠOOOOOОଠଠOoooᵒᵒᵒᵒᵒᵒᵒᵒᵒ ⛪⛪⛪⛪⛪👼👼👀🙏🙏💒💒💒💒 Pope shit',
  '🎥👀🎥👀🎥👀🎥👀🎥👀 good shot go౦ԁ sHot🎬 thats 🎬 a good🎥🎥shot right🎬📼 th 📷 ere🎥🎥 right 🎬 there 📼🎥 if i do ƽaү so my selｆ 📼 i say so 🎬 thats what im talking about right there right there (chorus: ʳᶦᵍʰᵗ ᵗʰᵉʳᵉ) mMMMMᎷМ🎬 📷📹📼НO0ОଠＯOOＯOОଠଠOoooᵒᵒᵒᵒᵒᵒᵒᵒᵒ 🎥🎥🎥 🎬 🎬 👀👀Good shot',
  '💦😫💦😫💦😫💦😫💦😫 desperate shit desperate sHit💦 thats 🙏 some desperate💦💦shit right💦💦there💦💦💦 right🙏there 🙏🙏if i do ƽaү so my self 🏊 i say so 🏃 thats what im talking about right there right there (chorus: ʳᶦᵍʰᵗ ᵗʰᵉʳᵉ) mMMMMᎷМ🏊 💦💦 💦НO0ОଠOOOOOОଠଠOoooᵒᵒᵒᵒᵒᵒᵒᵒᵒ💦💦💦💦 🙏 💦 😩😫😩 💦💦desperate shit',
  '🚪🚫🚪🚫🚪🚫🚪🚫🚪🚫 door stuck door sTuck🚪 please 🔪 i beg you🚪🚪we’re dead🚪🚪door stuck🚪🚪🚪 door🔪stuck 🔪🔪i tried to sneak through the door man 🔫 can’t make it 🔫 outta my way son you’re a genuine door stuck (chorus: ᵈººʳ ˢᵗᵘᶜᴷ) mMMMMᎷМ🔫 🚪🚪 🚪НO0ОଠOOOOOОଠଠOoooᵒᵒᵒᵒᵒᵒᵒᵒᵒ🚪 🚪🚪 🚪🔫 🚪 🚫 🚫 🚫 🚪🚪Door stuck',
  '👌🍞👌🍞👌🍞👌🍞👌🍞 garlic bread gaRlic bRead👌 thats ✔ some garlic👌👌bread right👌👌there👌👌👌 right✔there ✔✔if i do ƽaү so my self 💯🍞 i say so 🍞 thats what im talking about right there right there (chorus: ʳᶦᵍʰᵗ ᵗʰᵉʳᵉ) mMMMMᎷМ 🍞 👌👌 👌НO0ОଠOOOOOОଠଠOoooᵒᵒᵒᵒᵒᵒᵒᵒᵒ👌 👌👌 👌 🍞 👌 🍞 🍞 🍞 👌👌Garlic bread',
  '⚓️🐳⚓️🐳⚓️🐳⚓️🐳⚓️🐳navy seal navy sEal ⚓️ thats⛵️ a navy ⚓️⚓️ seal right ⚓️⚓️ right ⛵️ there 🚤🚤 if I do ƽaү so myself 🚢 I say so 🚢 thats what im talking about right there right there (chorus: ʳᶦᵍʰᵗ ᵗʰᵉʳᵉ) mMMMMᎷМ ⚓️⚓️⚓⛵️️НO0ОଠOOOOOОଠଠOoooᵒᵒᵒᵒᵒᵒᵒᵒ ⚓️⚓️⚓️⚓️⛵️⚓️🐳🐳🐳⚓️⚓️ good shit',
  '🔪💀🔪💀🔪💀🔪💀🔪💀 gore shit go౦re sHit🔪thats ✔ some gore🔪🔪shit right🔪🔪there🔪🔪🔪 right✔there ✔✔if i do ƽsaү so my self 💉 i say so 💉 thats what im talking about right there right there (chorus: ʳᶦᵍʰᵗ ᵗʰᵉʳᵉ) mMMMMᎷМ💉🔪🔪 🔪НO0ОଠOOOOOОଠଠOoooᵒᵒᵒᵒᵒᵒᵒᵒᵒoo🔪🔪🔪 💉 🔪 💀💀 💀 🔪Gore shit',
  '🔥🌋🔥🌋🔥🌋🌋🔥🌋 pyromancer shit pyromancer sHit🔥 thats 🌋 some pyromancer 🔥🔥shit right🔥🔥th 🔥 ere🔥🔥🔥 right🌋 there 🌋🌋if i do ƽaү so my selｆ 🌋 i say so 🌋 thats what im talking about right there right there (chorus: ʳᶦᵍʰᵗ ᵗʰᵉʳᵉ) mMMMMᎷМ🌋 🔥🔥 🔥НO0ОଠＯOOＯOОଠଠOoooᵒᵒᵒᵒᵒᵒᵒᵒᵒ🔥🔥🔥🔥 🌋🔥 🌋🌋🌋 🔥🔥pyromancer shit',
  '📚📖 📖 📚📖 📚📖calculus shit tHat’s sum cAlcuLUς $#!t📚 thats∰some good∰∭integration right∳∰there 📚 📚 📚right⨌there⨍find the limit📖find the📖limit📖that’s not showing your work right tᴴᵉᴿe 📖📖 show w0rk(chorus: ᵍᴵᵛᴱn f⁽ˣ⁾ax)mMMMMMM📖∰∯∰ НO0ОଠOOOOOОଠଠOoooᵒᵒᵒᵒᵒᵒᵒᵒᵒ📚📚📚📚∰📖☕☕☕☕☕☕☕☕GOnnA FaIL',
  '😬😳🙊😥😬🙊🙊🙊😬😥 awkward shit awkward sHit😬 thats 🙊some awkward😬😬shit right😬😬th 😬 ere😬😬😬 right💬there 💬💬if i do ƽaү so my selｆ 😳 i say so 😳 thats what im talking about right there right there (chorus: ʳᶦᵍʰᵗ ᵗʰᵉʳᵉ) mMMMMᎷМ🙊 😬😬😬НO0ОଠＯOOＯOОଠଠOoooᵒᵒᵒᵒᵒᵒᵒᵒᵒ😬😬 😬 🙊 😬😥🙊🙊😬😬awkward shit',
  '🌲👀🌲👀🌲👀🌲👀🌲👀 happy tree happy tRee🌲 thats ✔ some happy🌲🌲tree right🌲🌲there🌲🌲🌲 right✔there ✔✔if i do ƽaү so my self 💯 i say so 💯 thats what im talking about right there right there (chorus: ʳᶦᵍʰᵗ ᵗʰᵉʳᵉ) mMMMMᎷМ💯 🌲🌲 🌲НO0ОଠOOOOOОଠଠOoooᵒᵒᵒᵒᵒᵒᵒᵒᵒ🌲 🌲🌲 🌲 💯 🌲 👀 👀 👀 🌲🌲happy tree',
  '💩🐕💩🐕💩🐕💩🐕💩🐕 shitty shit dog sHit💩 thats ✖️ some dodgy doggy💩💩shit right💩💩th 💩 ere💩💩💩 right✖️there ✖️✖️if i do ƽaү so my selｆ ‼️ i say so ‼️ thats what im talking about right there right there (chorus: ʳᶦᵍʰᵗ ᵗʰᵉʳᵉ) mMMMMᎷМ‼️ 💩💩 💩HO0ОଠＯOOＯOОଠଠOoooᵒᵒᵒᵒᵒᵒᵒᵒᵒ💩 💩💩 💩 ‼️ 💩🐕🐕🐕 💩💩 shitty 5hit',
  '👊💪👊💪👊💪👊💪👊 Ez shit Ez sHit👊 thats 💪 some Ez 💪👍shit right👊👊there👈💪👊 rightthere if i do ƽaү so my self 💪👊 i say so👈👈 thats what im talking about right there right there 👈👈(chorus: ᴱᶻ) Ez 💪💪💪ᴱᴱᴱᴱᴱᴱᴱᴱᴱᴱᴱᴱᶻᶻᶻᶻᶻᶻᶻᶻᶻ👊👊👊👊👊 👈👈👈👊👊EZ shit👆',
  '💰🎆💰🎆💰🎆💰🎆💰🎆 good deals go౦ԁ dEals💰 there’s ✔ some good💰💰deals right💰💰there💰💰💰 right✔there ✔✔if i do ƽaү so my self 💯 i say so 💯 thats what im talking about right there right there (chorus: ʳᶦᵍʰᵗ ᵗʰᵉʳᵉ) mMMMMᎷМ💯 💰💰 💰НO0ОଠOOOOOОଠଠOoooᵒᵒᵒᵒᵒᵒᵒᵒᵒ💰 💰💰 💰 💯 💰 🎆 🎆 🎆 💰💰Good deals',
  '👿😱👿😱👿😱👿😱👿😱 scary shit scãry sHit👿 thats 💀 some scary👿👿shit right👿👿there👿👿👿 right💀there 💀💀if i do ƽaү so my self 💣 i say so 💣 thats what im talking about right there right there (chorus: ʳᶦᵍʰᵗ ᵗʰᵉʳᵉ) mMMMMᎷМ💣 👿👿 👌НO0ОଠOOOOOОଠଠOoooᵒᵒᵒᵒᵒᵒᵒᵒᵒ👿 👿👿 👿  💣 👿 😱 😱 😱 👿👿Scary shit',
  '🎆🎉🎆🎉🎆🎉🎆🎉 new year new year 🎉 thats 🎆 a new 🎉🎉 year right 🎉🎉 there 🎉🎉🎉 right🎆there 🎆🎆if I do say ƽo myself 🎊 I say so 🎊 thats the new year im talking about right there right there (chorus: ʳᶦᵍʰᵗ ᵗʰᵉʳᵉ) mMMMMᎷМ🎆 🎉🎉 🎉O0ОଠOOOOOОଠଠOoooᵒᵒᵒᵒᵒᵒᵒᵒᵒ🎉 🎉🎉🎉🎊 🎉 🎆🎆🎆 🎉🎉Happy New Year🎆',
  '⛄🎄⛄🎄⛄🎄⛄🎄 merry christmas mErry cHristmas⛄ thats ❄ some merry⛄⛄ christmas right⛄⛄there⛄⛄⛄ right❄there ❄❄if i do ƽaү so my self 🎁 i say so 🎁 thats what im talking about right there right there (chorus: ʳᶦᵍʰᵗ ᵗʰᵉʳᵉ) mMMMMᎷМ🎁 ⛄⛄ ⛄НO0ОଠOOOOOОଠଠOoooᵒᵒᵒᵒᵒᵒᵒᵒᵒ⛄ ⛄⛄⛄🎁 ⛄ 🎄🎄🎄 ⛄⛄Merry christmas',
  '😈🔥😈🔥😈🔥😈🔥😈🔥going to hell gOing to hEll 👇 goin👇👇 to hell 👇👇go⬇⬇ing to he🔥ll 🎻🎻 if i do say so myself 😈i say so 🔥 prayin cannot help me now (chorus: ʲᵉᵉᵇᵘˢ ʰᵃᶫᶫᵉᶫᵘʲᵃʰ) mMMMM MM ⛪ 🎻🔥HØOOoooOOoooOOO ⬇⬇⬇👇👇😈🔥😈🔥 goin to helL',
  '🐝👀🐝👀🐝👀🐝👀🐝👀🐝 bee shit bEe sHit👌 thats ✔ some good🐝🐝bee shit right🐝🐝th🐝 ere🐝🐝🐝 right✔there ✔✔if i do ƽaү so my selｆ 💯🐝 i say so 💯🐝 thats what im talking about right 🐝 there right there (chorus: ʳᶦᵍʰᵗ ᵗʰᵉʳᵉ) bBBBb💯🍯🍯🍯🐝BzzzZzzZZzzzᶻᶻᶻᶻᶻᶻᶻᶻᶻ💯🍯🍯🍯BZZzZ 🐝 💯 🐝 👀 👀 👀 💯🐝🐝Good bee shit',
  '🔯💵🔯💵🔯💵🔯💵🔯💵 oy vey Oy vEy🔯 thats 👃 some jewish🔯🔯 shit right🔯🔯 there🔯🔯🔯 right👃 there 👃👃 if i do ƽaү so my self 👴 i say so 👴 thats what im talking about right there right there (chorus: ᵐᵃᶻᵃᶫ ᵗᵒᵛ) mMMMMᎷМ👴🔯🔯🔯 НO0ОଠOOOOOОଠଠOoooᵒᵒᵒᵒᵒᵒᵒᵒᵒ🔯🔯🔯🔯👴🔯💵💵💵🔯🔯 Oy vey',
  '💪( ͡° ͜ʖ ͡°)💪( ͡° ͜ʖ ͡°)💪( ͡° ͜ʖ ͡°)💪( ͡° ͜ʖ ͡°) Kinky shit kinkY sHIt 💪 thatS 👉👌 Some kinky ( ͡° ͜ʖ ͡°) shit 👉👌 right ☺️ There ☺️☺️ if I do ƽaү so myself 👯 I say so 👯 if you know what im talking about 🍑🍌 right there 🍑🍌 right there (chorus: ʳᶦᵍʰᵗ ᵗʰᵉʳᵉ) mMMMMM 👯 ( ͡° ͜ʖ ͡°) НO0ОଠOOOOOОଠଠOoooᵒᵒᵒᵒᵒᵒᵒᵒᵒ ( ͡° ͜ʖ ͡°) ( ͡° ͜ʖ ͡°) 👉👌 😍☺️💪👅 kinky shit',
  '🍭🍬🍭🍬🍭🍬🍭🍬 sweet shit swEet sHit 🍭 thats 🍰 some sweet 🍭🍭 shit right 🍭🍭 th🍭ere 🍭🍭🍭 right🍰there🍰🍰 if i do  ƽaү so my selｆ 🍩i say so🍩thats what im talking about right there right there (chorus: ʳᶦᵍʰᵗ ᵗʰᵉʳᵉ) mMMMMᎷМ🍩 🍭🍭 🍭НO0ОଠＯOOＯOОଠଠOoooᵒᵒᵒᵒᵒᵒᵒᵒᵒ🍭 🍭🍭 🍭 🍩🍭 🍬🍬🍬 🍭🍭 Sweet shit',
  '📝📎📝📎📝📎📝📎📝📎 good paper go౦ԁ paPer📝 thats 💻 a good📝📝paper right📝📝th 📝 ere📝📝📝 right💻there 💻💻if i do ƽaү so my selｆ 💯 i say so 💯 thats what im talking about right there perfect grammar (chorus: ᵖᵉʳᶠᵉᶜᵗ ᵍʳᵃᵐᵐᵃʳ) mMMMMᎷМ💯 📝📝 📝НO0ОଠＯOOＯOОଠଠOoooᵒᵒᵒᵒᵒᵒᵒᵒᵒ📝 📝📝 📝 💯 📝 📎 📎📎 📎 📝📝Good paper',
  '👌🎩👓🎩👍🎩👓🎩👍🎩 euphoric logic !euphoric loGic👌 thats ✔ some euphoric👌💻 logic right👌💻there👌👍👌 Carl 🔭 Sagan🌌💫if i do ƽaү so gentlemen 💯 i say so 💯 thats euPhoric logic right there Richard 📒 Dawkins🎩 (chorus: ˢᵒᶜʳᵃᵗᵉˢ ᵈᶦᵉᵈ ᶠᵒʳ ᵗʰᶦˢ ˢʰᶦᵗ) mMMMMᎷМ💯 👌👓👌НO0ОଠOOOOOОଠଠOoooᵒᵒᵒᵒᵒᵒᵒᵒᵒ👌 👌🎩 👌 💯 👌 👓🎩🎩🎩 👍👌euphoric logic',
  '💻📊💻📊💻📊💻📊💻📊  thats 📒 some Excel-lent💻💻shit right💻💻th 💻 ere💻💻💻 right📒there 📒📒if i do 📊 ƽaү so my selｆ📒 i say so my 💻💻se 💻💻lf 📊 ledger en trie 📊 s 📊 📒 thats some verti📒 c a l 💻 shit right there 📊 right there (chorus: table_array) mMMMMᎷМ 📒 💻💻 💻 mmMmicr o sO0ОଠＯOOＯOОଠଠOoooᵒᵒᵒᵒᵒᵒᵒᵒᵒft 💻 💻💻 💻 📒 💻 📊 📊 📊 📒 💻💻Vertical shit',
  '🍟 🍔 🍕 🍔 🍕 🍔 🍕 🍔 🍕🍟 fat shit fAT sHit 🍖 thats🍪 some fat 🍰🎂 shit right🍫🍩there 🍧🍨🍮 right 🍪 there 🍖🍟 if I do say so my self 🍩 i say so 🍩 thats what im talking about right there right there (chorus: ʳᶦᵍʰᵗ ᵗʰᵉʳᵉ) mMMMMᎷm🍕🍟🍟🍟НO0ОଠOOOOOОଠଠOoooᵒᵒᵒᵒᵒᵒᵒᵒᵒ🍕🍟🍧🍨🍪🍖🍮🍰🍩🍫🍪🍧🍮🍨🍪 fat shit',
  '🔑🙏🔑🙏🔑🙏🔑🙏🔑🙏🔑success shit success sHit ✔ that some🔑🔑to success shit right🔑🔑there🔑🔑🔑right✔there ✔✔if i do bless up my self 🍏 i do bless up 🍏 thats another one right there right there (chorus: ʳᶦᵍʰᵗ ᵗʰᵉʳᵉ) mMMMMᎷМ🍏🔑🔑🔑НO0ОଠOOOOOОଠଠOoooᵒᵒᵒᵒᵒᵒᵒᵒᵒ🔑🔑🔑🔑🍏🔑🙏🙏🙏🔑🔑success shit',
  '🐜🙋🏼🌐🐜 🌐SpIder WeBs 🙋🏼🏡📞 🚫💤🏡📞 ⁽ʸᵉᵃʰ⁾ Sorry I’m not home right now🏡 📞🚫💤🏡 🚫💤I’m walking into spiderwebs 🙋🏼👠🐜🌐 👠📞So leave a message📥📞📥📞 and I’ll call you back  (ᶜᵃᶫᶫ ʸᵒᵘ ᵇᵃᶜᵏ) 📥 🐜🌐🐜🌐Leave a message and I’ll call you back ⁽ᶜᵃᶫᶫ ʸᵒᵒᵒᵒᵒᵘ ᵇᵃᵃᵃᵃᶜᵏ⁾🚫💤🏡🙋🏼🌐🐜',
  '🚨🚨🚨 WEE WOO WEE WOO WEE WOO 🚨🚨🚨 YOU ARE BEING DETAINED 💀💀🎺💀 FOR BEING AWAKE DURING REAL SPO0KY HOURS 🕐💀 PLEASE SHOW ME YOUR REAL SPO0KY REGISTRATION 🙉🎺💀 NO FUCCBOIS REAL SKELTONS ONLY!! IT DONT MATTER IF YOU DOOTING OR WHAT 💯💯💯',
  '📅This Sunday📆 We Set Our Clocks🕛🕑🕓🕕🕗🕙🕛 An Hour Forward ⏩ But Im Here To Tell You 💬 👆That Im 🚫 N O T 🚫Leaving Your Ass 🍑 Behind 💯💯 We Move On Together 👫 So When The Sun Goes Down 🌃 We Wake Up ✔️ Together ✔️ This Is Our Future 🌇🌅 This Is Our Time⌚️ Happy Daylight Savings 🎉🎊',
  '2015 was tuff 😓😰, challenqinq ‼️🙇, i learned wut love<3💕 💏 iz, wut pain 😩🔫 iz, i made new freinds 👫👫 <3 i lost some old freinds 🙅🙅 </3 i learned who i am 💁🏼👸 nd who i am not 😷. but no matter wut, i am who i am 😈. liv lyff w/ no reqretzz 👌. i am stronqer now 💪. cant wait 4 new year, new me 💁💁 <3; xoxo 😉',
  'You can\'t 〽 💲🀄ÜⓂ🅿 the Trump 📈💪🔥🔥 (liberal tears 😭😭💧💦🌊) BUILD 🔧👷🔨 WALL 🚪🚪🚪 BUILD A BIG ➕➕ BEAUTIFUL 💓💓💓 WALL 🚪🚪🚪🚪🚪 right there 👉🌎 (chorus: ʳᶦᵍʰᵗ ᵗʰᵉʳᵉ) Make America 🗽🗽 Great Again 💃👉 🚪 Trump 2016 📈☑☑☑',
  '😠😠😡😡🆘LIKE OH MY GOD👻👻❕❕ 😴WAKE UP😴 SHEEPLE CANT YOU 👀SEE 👀WHATS GOING ON😷😷?!? FIRST OFF IT IS 💯💯% 👍PROVEN👍 FACT THAT 🔯🔯JET✈✈ FUEL💦💦 🚫🚫CANT🚫🚫 MELT 🔥🔥STEEL BEAMS💥❕❕ LIKE JESUS CHRIST, THOSE WERE 👯💀CRISIS ACTORS💀👯 AT 🔪SANDY HOOK🔫❕❕ LIKE 😈LUCIFER😈 ALL MIGHTY, I CAN NAME OVER 💯 👮👮BLACK OPS 👮👮FALSE 🚩🚩FLAG OPERATIONS🚩🚩 OFF THE TOP OF MY HEAD!!! SERIOUSLY 😨WAKE😨 🆙!😭😭',
  'Water... 💧💦🌊 Earth... 🌎⚰⛰ Fire... 🔥☀️💥 Air. 🌪💨🌬 Long ago, 🕐🕜🕠 the 4️⃣ nationslived 2️⃣gether in harmony. 😊❤️ Then everything changed 😨😰 when the Fire 🔥💥 Nation attacked. ⚔💣😱 Only the Avatar, master of all 4️⃣ elements 💦🔥🌎🌪 could stop🚦them. But when the world 🌎🌍🌏 needed him most, he vanished. 😵 A hundred 💯 years 📅 passed and my brother 👦 and I 👸 discovered the🆕 Avatar 😊😌, an airbender 🌪🌬 named Aang. 😎🆒 And although his airbending🌪🌬 skills are great, 👍👌 he still has a lot to learn ✏️📝 before he\'s ready to save any1️⃣. 😀😀😀But I believe Aang can save the world. 😇🌎🌏',
  'OO mY, 😏 OH MY, i LOoOVE💘❤️💚 MY SEnpAI😏🙊✌️ KaAWAAII 🐠dESU DESU HEntai🐙 CHAN😜 how i want u TO nOtice 👀👌👀👌ME sEN PIE🍰 i WANT ur sQUIshy WASABI🎾😈 on my Sushi✊🍣🍤SPICY 🔥🔥🔥🔥leT’S mAKE sOME ORIGAMI😩😏🇯🇵 MY mASTER sENSEI 😯😑 DOKI DOkI tofU 😳🙀 ',
  '🐵🐒🐵🙊🐒🐵🐒🙈🙈🐵🐒 funny monkeys fUnnY m౦Nkeys🐵 thats ✔ some funny🙈🐵monkeys right 🙊🐵th 🐵 ere🙈🐵🙈 right✔there ✔✔if i do ƽaү so my selｆ 😂 i say so 😂 thats what im talking about right there right there (chorus: ʳᶦᵍʰᵗ ᵗʰᵉʳᵉ) mMMMMᎷМONKEY😂 🐵🐵 🙊 O0ОଠＯOOＯK OОଠଠOoooᵒᵒᵒᵒᵒᵒᵒᵒᵒk 🐵 🙊🐵 🐵 😂 🐵 🐒 🙊 🐒 🙈🙈Funny Monkeys',
  '💪😎🚬😎💪😎💪😎😎🚬 cool shit Co0l sh!t 💪😎 thats some ✔ cool 😎🚬shit RiGht th 😎 ere 💪😎🚬 rig ✔✔ht ✔ there ✔✔ if i do ƽaү so my selｆ🆒 i say so 🆒 thats what im talking about right there right thére (chorus: ʳᶦᵍʰᵗ ᵗʰᵉʳᵉ) mMMMMᎷМ 🆒😎💪😎🚬😎 НO0ОଠＯOOＯOОଠଠOoooᵒᵒᵒᵒᵒᵒᵒᵒᵒ 😎💪😎🚬🆒💪💪😎💪😎💪😎🚬😎💪 Cool Shit',
  '👀😯🤔😯🤔😯🤔😯🤔😯 wew lad weW lAD😯 thats 👌 some wew😯😯lad right😯😯th 😯 ere😯😯😯 right👌there 👌👌if i do ƽaү so my selｆ 👀 i say so 👀 thats what im talking about right there right there (chorus: ʷᴱʷ ˡᵃᵈ) hHMMMMMᎷМ👀 😯😯 😯WEeeEEeEEeeEeeᵂᵂᵂᵂᵂᵂᵂᵂᵂ😯 😯😯 😯 👀 😯 🤔 🤔 🤔 😯😯Wew lad',
  '🐶❤🐕🌈🌈🐶🐶❤🐕🌈 gay dogs gAy d0gs 🐶 thats ✔ some gay 🐶❤🐕 dogs right ❤🐕th 🌈  ere 🐶🐕🌈  rig ✔✔ht ✔ there ✔✔ if i do ƽaү so my selｆ 🐩 i say so 🐩 thats what im talking about right there right there (chorus: ʳᶦᵍʰᵗ ᵗʰᵉʳᵉ) mMMMMᎷМ 🐩❤🐕🌈🌈🌈❤🐕❤HO0ОଠＯOOＯOОଠଠOoooᵒᵒᵒᵒᵒᵒᵒᵒᵒ 🐶🌈❤🐶🐩❤❤🌈🐶❤🐕Gay dogs',
  '🚲🐸🚲🐸🚲🐸🐸🚲🐸🚲 dat boi Dat b0iiii🐸 thats ✔ dat 🚲🐸 boiii right 🚲🐸 th 🐸 ere 🚲🐸🐸 right✔there ✔✔if i do ƽaү so my selｆ🚲 i say so 🐸 if i do ƽaү so my selｆ😂 i say so 😂 thats what im talking about right there right there (chorus: ଠ sʰᶦᵗ) mMMMMᎷМ 😂🚲🐸🚲🐸🚲🐸🐸НO0ОଠＯOOＯOОଠଠOoooᵒᵒᵒᵒᵒᵒᵒᵒᵒ 🚲🐸🚲🚲😂🐸🐸🚲🐸🚲🐸 O shit waddup',
  '🌬🌿 🌬🌿 🌬🌿 🌬🌿 🌬🌿  vape nation vAPe natI౦n🌬 thats 🍃 some vape🌬🌬nation yall right🌬🌬th 🌬 ere🌬🌬🌬 right🍃there 🍃🍃if i do ƽaү so my selｆ 💯 i say so 💯 thats what im talking about right there yall (chorus: ᴳᴼ ᴳᴿᴱᴱⁿ) mMMMMᎷМ💯 🌬🌬 🌬НO0ОଠＯOOＯOОଠଠOoooᵒᵒᵒᵒᵒᵒᵒᵒᵒ🌬 🌬🌬 🌬 💯 🌬 🌿  🌿  🌿  🌬🌬Vape nation',
  '💰💰🤑 💵 🤑💰💰💵💰🤑🤑rich shit R1ch $hit💰🤑thats  💎 some rich💰💵 shit🤑🤑right th 💰 ere🤑💰💵right 💎there 💎💎if i do ƽaү so my selｆ 💳 i say so 💳 thats what im talking about right there right there (chorus: ʳᶦᵍʰᵗ ᵗʰᵉʳᵉ)mMMMMᎷМ💳💰💵🤑🤑🤑💰💵 HO0ОଠＯOOＯOОଠଠOoooᵒᵒᵒᵒᵒᵒᵒᵒᵒ 💵💰💵💳🤑💰💵💵💰💰💵Rich shit',
  '👴😍 🆓 💩 👴🆓 💩🆓 💩😍👴 bernie sanders bErnié sANdeRs 🆓 💰 thats ✔ some bernie 😍🆓👴 shit 🆓 💩 right th 👴 ere 😍 🆓 💩 right✔there ✔✔if i do ƽaү so my selｆ 🆓 i say so 🆓 thats what im talking about right there right there (chorus: ʳᶦᵍʰᵗ ᵗʰᵉʳᵉ) mMMMMᎷМ 🆓💩👴👴🆓💰O0ОଠＯOOＯOОଠଠOoooᵒᵒᵒᵒᵒᵒᵒᵒᵒ 👴💰🆓💩🆓💩👴💩🆓Bernie shit',
  '👨‍❤️‍👨🌈👨‍❤️‍💋‍👨🌈🌈👨‍❤️‍👨🌈❤️‍ gay shit gⓐY shIt 👨‍❤️‍👨🌈 thats ✔ some gay 🌈👨‍❤️‍💋‍👨 shit ❤️‍👨‍❤️‍👨🌈 right th 🌈 ere 👨‍❤️‍💋‍👨❤️‍❤️‍ right✔there ✔✔if i do ƽaү so my selｆ 👨‍👨‍👦 i say so 👨‍👨‍👦 thats what im talking about right there right there (chorus: ʳᶦᵍʰᵗ ᵗʰᵉʳᵉ) mMMMMᎷМ 👨‍👨‍👦🌈❤️‍👨‍❤️‍👨🌈O0ОଠＯOOＯOОଠଠOoooᵒᵒᵒᵒᵒᵒᵒᵒᵒ 👨‍❤️‍💋‍👨❤️‍👨‍❤️‍👨🌈👨‍👨‍👦👨‍❤️‍👨🌈❤️‍🌈🌈👨‍❤️‍👨 Gay shit',
  '🍣🍙🍱🍚🍙🍚🍱🍣 weeaboo shit wEEaBoo sHiT 🍚🍱 thats 🗾 some weeaboo🍚🍙shit🍣🍚right th 🍙 ere🍙🍱right🗾there 🗾🗾if i do ƽaү so my selｆ 🇯🇵 i say so 🇯🇵 thats what im talking about right there right there (chorus: ʳᶦᵍʰᵗ ᵗʰᵉʳᵉ) mMMMMᎷМ🇯🇵🍙🍣🍣🍱🍚 HO0ОଠＯOOＯOОଠଠOoooᵒᵒᵒᵒᵒᵒᵒᵒᵒ 🍣🍱🍙🍣🇯🇵🍱🍣🍙🍱🍙🍣Weeabo shit',
  '🏉🏏🐊🇦🇺🇦🇺🐊🐍🐍🕷  aussie shit aUssiE ShIT🐍🕷 thats some✔aussie🐊🇦🇺shit RiGht th 🏉 ere 🏏🇦🇺🐍 rig ✔✔ht✔there✔✔ if i do ƽaү so my selｆ ☀ i say so ☀ thats what im talking about right there right there (chorus: ʳᶦᵍʰᵗ ᵗʰᵉʳᵉ) mMMMMᎷМ ☀🐍🇦🇺🐊 O0ОଠＯOOＯOОଠଠOoooᵢᵢᵢᵢᵢᵢᵢᵢᵢᵢᵢᵢᵢᵢᵢ 🕷🏏🇦🇺🕷☀🐊🐊🏏🏉🇦🇺🐍🕷Aussie Shit',
  '👨🏿💽 👨🏿💽 👨🏿💽 👨🏿💽 👨🏿💽  kanye west kanYe wEst👨🏿thats 🎤 some kanye👨🏿👨🏿west right👨🏿👨🏿th 👨🏿 ere👨🏿👨🏿👨🏿 right🎤there 🎤🎤if i do ƽaү so my selｆ 💍 i say so 💍 imma let you finish right there right there (chorus: ᴵ ᵃᵐ ᵃ ᵍᵒᵈ) mMMMMᎷМ💍 👨🏿👨🏿 👨🏿НO0ОଠＯOOＯOОଠଠOoooᵒᵒᵒᵒᵒᵒᵒᵒᵒ👨🏿 👨🏿👨🏿 👨🏿 💍 👨🏿 💽  💽  💽  👨🏿👨🏿Kanye west',
  '🐼🎍 🐼🎍 🐼🎍 🐼🎍 🐼🎍  panda shit panDa sHit🐼thats 😴 some panda🐼🐼shit right🐼🐼th 🐼 ere🐼🐼🐼 right😴there 😴😴if i do ƽaү so my selｆ 🇨🇳 i say so 🇨🇳 thats what im talking about right there right there (chorus: ʳᶦᵍʰᵗ ᵗʰᵉʳᵉ) mMMMMᎷМ🇨🇳 🐼🐼 🐼НO0ОଠＯOOＯOОଠଠOoooᵒᵒᵒᵒᵒᵒᵒᵒᵒ🐼 🐼🐼 🐼 🇨🇳 🐼 🎍  🎍  🎍  🐼🐼Panda shit',
  '🐠🐟🐡🐟🐠🐟🐠🐡🐠🐡🐟🐠🐟 fishy shit fIShy sHiT 🐠 thats🐟some✔fishy🐟🐠shit right🐠🐟th 🐠 ere🐠🐟🐠 right🐠there 🐟🐡if i do ƽaү so my selｆ 🎣 i say so 🎣 thats what im talking about right there right there (chorus: ʳᶦᵍʰᵗ ᵗʰᵉʳᵉ) mMMMMᎷМ🎣🐟🐡🐠🐟🐡НO0ОଠＯOOＯOОଠଠOoooᵒᵒᵒᵒᵒᵒᵒᵒᵒ🐠🐡🐟🐡🎣🐡🐟🐠🐠🐟🐡🐠🐟🐟🐡🐠 Fishy shit',
  '😷💪😷💪😷💪😷💪😷💪 big guy biG gUy😷 im 🔥 a big😷😷guy for😷😷yo 😷 u😷😷😷 for🔥you 🔥🔥if i do ƽaү so my selｆ ✈ i say so ✈ if i took that off would you die (chorus: ᶠᵒʳ ʸᵒᵘ) mMMMMᎷМ✈ 😷😷 😷НO0ОଠＯOOＯOОଠଠOoooᵒᵒᵒᵒᵒᵒᵒᵒᵒ😷 😷😷 😷 ✈ 😷 💪 💪 💪 😷😷For you',
  '🍉🍗🍉🍗🍉🍗🍉🍗🍉🍗black shit BlaCK ShIt🍉thats🚗some🚗black🍉🍉shit right🍗🍉 th 🍉 ere🍉🍗🍉right🚗there🚗🚗if i do ƽaү so my selｆ🏀 i say so 🏀 thats what im talking about right there right there (chorus: ʳᶦᵍʰᵗ ᵗʰᵉʳᵉ)mMMMMᎷМ🏀🍗🍗🍉НO0ОଠＯOOＯOОଠଠOoooᵒᵒᵒᵒᵒᵒᵒᵒᵒ🍗🍉🍗🍉🏀🍗🍗🍉🍗🍉🍉Black shit',
  '🏄🌊🏄🌊🏄🌊🏄🌊🏄🌊wavy dude WAVY duDe🌊thats🏄one😎wavy🌊🏄dude right🌊🏄 th 🏄 ere🏄🌊🌊right 😎there😎😎if i do ƽaү so my selｆ🐻 i say so 🐻 i know youre going to keep it loopy (chorus: ʷᵃᵛʸ, ᵇᵃᵇʸ)mMMMMᎷМ🐻🌊🏄🏄🌊НO0ОଠＯOOＯOОଠଠOoooᵒᵒᵒᵒᵒᵒᵒᵒᵒ🌊🌊🏄🌊🐻🏄🌊🌊🏄🌊🏄🌊Wavy Dude',
  '🎲🎰🎲🎰🎲🎰🎲🎰🎲🎰 lucky shit LUCky SHit🎰thats ✔ some lucky🎰🎲shit right🎲🎰th 🎲 ere🎰🎰🎰 right✔there ✔✔if i do ƽaү so my selｆ 🍀 i say so 🍀 thats what im talking about right there right there (chorus: ʳᶦᵍʰᵗ ᵗʰᵉʳᵉ) mMMMMᎷМ🍀🎲🎰 🎲НO0ОଠＯOOＯOОଠଠOoooᵒᵒᵒᵒᵒᵒᵒᵒᵒ🎰 🎰🎲 🎰 🍀 🎰 🎲  🎰  🎲  🎰🎰Lucky shit',
  '🏈💑🏈💑🏈💑🏈💑 normie shit NoRMiE SHit🏈thats 💪 some normie💑🏈shit right💑🏈th 💑 ere🏈🏈💑 right💪there 💪💪if i do ƽaү so my selｆ 💰 i say so 💰 thats what im talking about right there right there (chorus: ʳᶦᵍʰᵗ ᵗʰᵉʳᵉ) mMMMMᎷМ💰💑🏈 🏈НO0ОଠＯOOＯOОଠଠOoooᵒᵒᵒᵒᵒᵒᵒᵒᵒ🏈 💑🏈💑 🏈 💰 💑 🏈 💑 💑  🏈🏈Normie shit',
  '💉💊💉💊💉💊💉💊💉💊 druggie shit DRuGgie SHIt💊thats 🌿 some druggie💊💉shit right💊💉th 💉 ere💊💉💊 right🌿there 🌿🌿if i do ƽaү so my selｆ 🍄 i say so 🍄 thats what im talking about right there right there (chorus: ʳᶦᵍʰᵗ ᵗʰᵉʳᵉ) mMMMMᎷМ🍄💉💉 💊НO0ОଠＯOOＯOОଠଠOoooᵒᵒᵒᵒᵒᵒᵒᵒᵒ 💉 💉💉 💊 🍄 💉 💊 💉 💊  💊💉Druggie shit',
  '🐦🐤🐦🐤🐦🐤🐦🐤🐦🐤  dinosaur shit DINoSauR SHIT🐦thats 🕊 some dinosaur🐤🐤shit right🐦🐤th 🐦 ere🐦🐤🐦 right🕊there 🕊🕊if i do ƽaү so my selｆ 🐧 i say so 🐧 thats what im talking about right there right there (chorus: ʳᶦᵍʰᵗ ᵗʰᵉʳᵉ) mMMMMᎷМ🐧🐤🐤 🐦НO0ОଠＯOOＯOОଠଠOoooᵒᵒᵒᵒᵒᵒᵒᵒᵒ 🐦 🐦🐤 🐦 🐧 🐦 🐤 🐤 🐦  🐤Dinosaur shit',
  '🌶🍛🌶🍛🌶🍛🌶🍛🌶🍛  spicy shit SPICy shiT🍛thats ✔ some spicy🌶🍛shit right🌶🌶th 🍛 ere🌶🍛🌶 right✔there ✔✔if i do ƽaү so my selｆ 🔥 i say so 🔥 thats what im talking about right there right there (chorus: ʳᶦᵍʰᵗ ᵗʰᵉʳᵉ) mMMMMᎷМ🔥🌶🌶 🍛НO0ОଠＯOOＯOОଠଠOoooᵒᵒᵒᵒᵒᵒᵒᵒᵒ 🌶 🍛🍛 🌶 🌶 🍛 🌶🔥 🍛 🌶  🍛Spicy shit',
  '⚗🔬⚗🔬⚗🔬⚗🔬⚗🔬 science shit SCIenCe shIT⚗thats 📚 some science🔬⚗shit right🔬🔬th ⚗ ere🔬⚗🔬 right📚there 📚📚if i do ƽaү so my selｆ 🔭 i say so 🔭 thats what im talking about right there right there (chorus: ʳᶦᵍʰᵗ ᵗʰᵉʳᵉ) mMMMMᎷМ🔭⚗⚗ ⚗НO0ОଠＯOOＯOОଠଠOoooᵒᵒᵒᵒᵒᵒᵒᵒᵒ 🔬 ⚗⚗ 🔬 🔭 ⚗ 🔬🔬 ⚗ 🔬  ⚗Science shit',
  '👴👧👴👧👴👧👴👧👴👧  pedo shit PEdO ShiT👴thats 🍬 some pedo👴👧shit right👧👴th 👧 ere👴👧👴 right🍬there 🍬🍬if i do ƽaү so my selｆ 🔞 i say so 🔞 thats what im talking about right there right there (chorus: ʳᶦᵍʰᵗ ᵗʰᵉʳᵉ) mMMMMᎷМ🔞👴👴 👧НO0ОଠＯOOＯOОଠଠOoooᵒᵒᵒᵒᵒᵒᵒᵒᵒ 👴 👧👴 👧 🔞 👧 👴 👴 👧  👧Pedo shit',
  '💝👰💝👰💝👰💝👰💝👰 waifu shit waiFu sHit 💝thats ✨ some kawaii💝💝shit right💝💝there 💝💝💝right✨there ✨✨if i do ƽaү so my self💐  i say so💐  thats what im posting about right there right there (chorus: ˢʰᵉ ᵃ ᶜᵘᵗᵉ) deSsSS💐💝💝UUuUUᴜᴜuUUᴜᴜUUᴜᴜuᴜᴜᴜᵤᵤᵤᵤᵤᵤᵘᵘᵘᵘᵘuᵘᵘ💝💝💝💝💐 💝👰💝👰👰👰Waifu shit',
  '⛵💕⛵💕⛵💕⛵💕⛵💕 cute boat cute bOat💕 thats 💖one cute💕💕boat right💕💕th 💕 ere💕💕💕right💖there 💖💖if i do ƽaү so my selｆ 💋 i say so 💋 thats what im talking about right there right there (chorus: ʳᶦᵍʰᵗ ᵗʰᵉʳᵉ) mMMMMᎷМ💋 💕💕💕НO0ОଠＯOOＯOОଠଠOoooᵒᵒᵒᵒᵒᵒᵒᵒ💕💕💕 💋 💕 ⛵⛵⛵💕💕Cute boat'
];
