exports.run = (client, message, Discord) => {
    const embed = new Discord.RichEmbed()
        .setAuthor("Commands", client.user.displayAvatarURL)
        .setDescription(`Use \`~help <command name>\` or \`~help <category name>\` for more details.`)
        .setColor('727293')
        .setThumbnail(client.user.displayAvatarURL)
        .setFooter("Any message from me can be removed by reacting with a 🎴 emoji.")
        .addField("__Info:__", "`commands` `help` `support`", true)
        .addField("__Moderation:__", "`ban` `kick` `prune` `warn`", true)
        .addField("__Utility:__", "`color` `time` `translate` `weather`", true)
        .addField("__Search:__", "`img` `osu` `wiki` `urban` `youtube`", true)
        .addField("__Fun:__", "`8ball` `cat` `dog` `f` `horoscope` `meme` `rate` `rightthere` `say` `talk`")
        .addField("__Memes:__", "`bonzi` `disabled` `retarded` `shit` `shits` `thesearch` `triggered`")
        .addField("__Anime:__", "`anime` `catgirl` `moe` `quote` `safebooru` `speak` `suggest` `zr`", true)
        .addField("__Action:__", "`cuddle` `grope` `hand` `hug` `kiss` `lewd` `pat` `slap` `smug`", true)
        .addField("__2D NSFW:__", "`ahegao` `danbooru` `hentai` `hentaiirl` `neko` `rule34` `trap`", true)
        .addField("__3D NSFW:__", "`ass` `boobs` `nsfw` `nsfwgif`", true)
    return message.channel.send({embed}).then(m=>m.react("🎴"))
}